### ISSUE TITLE
Integration with DOJ SMTP servers

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#118]
As a [user], in order to [accomplish some goal], I need [some feature].

## Acceptance criteria

- [x] Emails sent out by Drupal should be sent through DOJ's SMTP servers
- [x] The sum of all attachments on request forms should not exceed 20MB

## Functional Review

- [x] Login to dev
- [x] Go to /node/6956/edit
- [x] Enter your email address for the "Submission Email" field
- [x] Go to `/form/test-form`
- [x] Submit the form with all fields filled out (including an attachment)
- [x] Go to `/admin/content/foia-requests`
- [x] Verify there is a FOIA request corresponding to your submission with a status of "Queued for submission"
- [x] Ping Malik or Dan to run the process that sends out emails, or, run it with the following command:
```
drush @foia.dev queue-run foia_submissions -vvv
```

- [x] Wait a couple of minutes
- [x] Check your email and verify you received an email containing your submission contents,
 as well as the attachment

## Developer Review
- [x] Review [PR 106](https://github.com/usdoj/foia-api/pull/106)

*Setup*
N/A, 118 is already deployed to dev

*Testing*
- [x] Complete functional review steps

*Automated Testing*
- [x] Run `blt tests:all` and verify that all tests are passing

**Comment by malikkotob** [comment]
This is blocked until we know which 3rd party email service we will be going with.

**Comment by kristusacquia** [comment]
Currently blocked pending selection of a 3rd party email service by DOJ.

**Comment by malikkotob** [comment]
Merged into `develop`.
