### ISSUE TITLE
Identify long-term strategy for onboarding agencies to the FOIA platform

### ISSUE THREAD

**Issue by adborden** [usdoj/foia.gov#14]
There are multiple levels of integration with an agency and the Portal. Ideally, every agency would be integrated via API so that requests from the Portal were entered directly into the agency's case management system without the need for manual data entry. It will be an ongoing effort to get all agencies to that level of integration. OIP will be the one to champion this strategy and needs to be equipped to do so.

- [ ] Docs for OIP to configure an agency for API access
- [ ] Docs for agencies on how to reach out to OIP and start the build process

**Comment by adborden** [comment]
@pkarman  suggested one part of this could be an onboarding document for agencies. @pkarman do you having any initial thoughts on what that might include?

**Comment by pkarman** [comment]
It might be helpful to create some documentation or other artifacts as we go through the manual onboarding process when our first pilot agencies.

**Comment by adborden** [comment]
This came up in conversation as we were talking about onboarding agencies for the API during FY18 with limited resources. I added a few areas where docs would be helpful.
