### ISSUE TITLE
Cannot use `make serve` with a custom APP_ENV value

### ISSUE THREAD

**Issue by mrclay** [usdoj/foia.gov#1582]
`APP_ENV=ddev make build` correctly builds for local API usage, but `make serve` (technically the `serve:watch` script) always overwrites the build using `APP_ENV=dev`.

## Expected Behavior

I would expect if I set `export APP_ENV=ddev` then build and serve to honor that.

## Actual Behavior

I have to use `make serve.dev` to (ironically) serve the DDEV build.

## Steps to reproduce the behavior

1. `export APP_ENV=ddev`
1. `make build` (ddev config is used)
1. `make serve` (dev config is used in the watch build)

I guess I need to know how this _should_ work before sending a PR :)

**Comment by ameshkin** [comment]
I'm going to close this issue since this was fixed a while back.  Please let us know if there are any other changes you would like.
