### ISSUE TITLE
Preferred state management library for react development?

### ISSUE THREAD

**Issue by mrclay** [usdoj/foia.gov#1646]
As the Forum One team plans to build a new wizard to help users find/create FOIA requests, we'd like to know your team's preference on state management (and if their are strong opinions there). 

I see most foia.gov React code using the now-archived [Flux library](https://facebookarchive.github.io/flux/), but the creators now recommend authors use some other maintained solution. I personally think the small [Zustand](https://github.com/pmndrs/zustand) library (1.2kb bundled) would be a good fit for our needs, or maybe [Redux Toolkit](https://redux-toolkit.js.org/) as a more popular one, but I totally understand if y'all would prefer keeping the same flux patterns across the board.

What are your thoughts here?

**Comment by brockfanning** [comment]
@mrclay No preferences here. If you think that Flux and Zustand/Redux can co-exist in the same application, I think it would be great for you to use Zustand/Redux, and then we can switch over the Flux stuff afterwards. If you don't think they can co-exist then it gets trickier, as we'd have to switch everything else over at the same time.

**Comment by mrclay** [comment]
:+1:  Coexistence should be no problem.

**Comment by brockfanning** [comment]
Ok, we're happy then to go with your preferred library, as long as it has reasonable open-source community support.
