### ISSUE TITLE
Scan files for viruses prior to sending out via API

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#189]
As a [user], in order to [accomplish some goal], I need [some feature].

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by adborden** [comment]
Agencies should have similar security controls on their end already implemented, so we're looking for guidance from DOJ on what requirements we need on our side.

**Comment by malikkotob** [comment]
Duplicate of #459
