### ISSUE TITLE
Identify pilot agencies for metadata management

### ISSUE THREAD

**Issue by pkarman** [usdoj/foia.gov#19]
- [x] The agencies should reflect a mix of agencies

* centralized vs decentralized
* different request mechanisms:
    * FOIAonline users
    * FOIAxpress users
    * FOIAxpress w/PAL users
    * custom case management
    * manual users

- [x] The list should include agencies willing to help by providing feedback and agencies willing to pilot the metadata form and give us frank feedback

**Comment by bsweger** [comment]
Note: go through survey results to identify targets and do outreach to get them on board

**Comment by vz3** [comment]
@vz3 should spike w @pkarman

**Comment by vz3** [comment]
@vz3 should have a 1:1 with Matt on this
