### ISSUE TITLE
Identify authentication mechanism for agency data editing

### ISSUE THREAD

**Issue by pkarman** [usdoj/foia.gov#20]
The built-in Drupal password authentication features may be sufficient, but a security analysis vis-a-vis ATO should be performed to evaluate.

- [ ] Identify ATO officials
- [ ] Identify the security team
- [ ] Identify what documentation the security team will need for ATO
- [ ] Provide a recommendation for authentication mechanism (Drupal)

**Comment by vz3** [comment]
Consider breaking out a related issue around designing the login experience.

**Comment by ba66e77** [comment]
@bsweger, I understand DOJ has taken this as an action item and is giving serious consideration to max.gov.   is that your understanding as well?

**Comment by bsweger** [comment]
@ba66e77 Yep, DOJ is still, I believe, in the process of identifying the security folks we'll be working with (will on that in standup/sync today).

It sounds like max.gov is an option on the table but that we need more info about what the specific requirements are. The only thing I've seen to that end so far is the generic list of security stories that Arshad posted.

**Comment by bsweger** [comment]
Looks like a security person will join us at sync on 8/8. @adborden and I started a list of questions here: https://docs.google.com/document/d/19_RsXMAu7eVwa97vpv36HsB9Xtnno7oSK4ocdNCkDX0/edit#

**Comment by adborden** [comment]
@leahbannon I think this is done... the next steps are up to the C&A folks, with @malikkotob leading the implementation.
