### ISSUE TITLE
Define rules for web form editing

### ISSUE THREAD

**Issue by pkarman** [usdoj/foia.gov#21]
The [Drupal webform module](https://www.drupal.org/project/webform) may be a good starting place for this feature. It should be evaluated with an eye to minimizing the number of user-exposed features and simplified UI.

The [original suggestion](https://github.com/18F/foia-recommendations/blob/master/schemas.md#uischema-for-form-presentation) for presenting form metadata was [uiSchema](https://github.com/mozilla-services/react-jsonschema-form#the-uischema-object), but regardless of whether it is incorporated, preference should be given to an open standard exchange format for serializing the form metadata. In particular, we need to able to capture any regulatory URLs or references as part of the metadata for any particular field, in addition to presentation attributes.

**Comment by ba66e77** [comment]
For serialization, once we have the element details into the database we can pull them out in whatever format is desired.

For minimizing user features...

Here's a run down of what Webform ships with out of the box: https://www.drupal.org/node/2837024

When editing a form, the UI looks as shown below.  When "Add element" is selected the user is presented with a list of available field types to select from.
![basic_request_submission_form___foia_gov](https://user-images.githubusercontent.com/1698983/28573111-841c0e30-7117-11e7-8b30-f8741e3c4f46.png)

For regulatory URLs and references, we've thus far imagined using the Description element associated with each field for those.  You can see how that approach looks in the form below.  in this example we're giving regulation detail about the email field.  By default that text appears below the field but repositioning it is a a configuration option.

![basic_request_submission_form___foia_gov 2](https://user-images.githubusercontent.com/1698983/28573247-07d3aada-7118-11e7-9973-4de44ad049f2.png)

**Comment by pkarman** [comment]
I like the use of `Description` for the field to store regulatory information. Maybe we can establish some strong conventions for how to phrase or describe that text as part of the agency usability tests.

**Comment by tram** [comment]
If the term we use is fairly neutral, during agency sessions, we can listen for how they describe it to us and each other then change the term to fit.

**Comment by pkarman** [comment]
I think the Drupal element is called `Description` but presumably we can change how it is labeled and provide prompting example text.

**Comment by bsweger** [comment]
Deferring this until design exercises are complete (also see #17)

**Comment by bsweger** [comment]
@vz3 I _thought_ this ticket was about the interface for agencies to update their metadata (_i.e._, not about the FOIA form used by requesters), but agreed that it's not clear by reading the description.

@pkarman please jump in if I'm wrong about that.

Re: "design exercises," I think that refers to OIP's directive that the self-service agency metadata prototype be easier to use before we show it to offices. @tram may have more insight into the specifics.

**Comment by pkarman** [comment]
Yes, this is the UI for managing the agency metadata that describes the questions they ask FOIA requesters (the Request Form).

We know that the existing Drupal UI is not sufficient. This ticket represents the data modeling and UI modeling required to know what is ok to ask of agency FOIA officers when they are trying to give us their FOIA Request Form metadata.

E.g., should every question be a open-ended text field? Should there be predefined dropdown list for a particular field? How should the prompt for "next question please" be displayed to the FOIA officer?

**Comment by vz3** [comment]
Still confused between #17 and #21 at the moment will jump to Slack.
