### ISSUE TITLE
Research direction activity

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#28]
As a team we need to decide what to research and test in the coming weeks. Specifically, we'd like to get input on what questions to ask and what to show folks. @AvivaOskow has suggested an activity using Mural or the like during a team meeting.

**Comment by AvivaOskow** [comment]
I think we need a fresh start in terms of the research planning from the discovery sprint, the shuffling of the architecture conversation with the partners, all of our new team members, and now our entry into build.

I suggest we do a facilitated research planning session in mural.ly that we can all participate by using a simple journey map (think key moments) from the requester side, as well as the agency side, where we can iterate on what questions we have at each point. This will help us determine what questions we need to focus on for research next, as well as give us all a fuller picture of the ecosystem we are working within. We can then prioritize, and zoom in and out of these key moments to help determine what to focus on each sprint.
