### ISSUE TITLE
Provide CWS team with README documentation in Word format

### ISSUE THREAD

**Issue by adborden** [usdoj/foia.gov#294]
CWS would prefer the documentation in Word format, so we should copy the README content of our repos to a Word doc.

## Acceptance criteria

- [ ] beta.foia.gov READMEs
- [ ] foia-api READMEs

**Comment by adborden** [comment]
@malikkotob @kristusacquia does this plan make sense with what you were thinking?

**Comment by brockfanning** [comment]
I don't know why this would be needed, so I'm going to close this. Please re-open if there is some reason that I'm missing.
