### ISSUE TITLE
No skin, start/stop/cation button, shown on all flash video

### ISSUE THREAD

**Issue by jhuang0427** [usdoj/foia.gov#313]
File, SkinUnderPlayStopSeekCaptionVol.swf, need to be on root folder of web site.

**Comment by adborden** [comment]
@jhuang0427 do you want to submit a PR for this? You would just drop the file under `/www.foia.gov/`.

**Comment by jhuang0427** [comment]
@adborden Yes, will submit later.

**Comment by jhuang0427** [comment]
@adborden @brockfanning I have tried to push back, but I got the error as following,
remote: Permission to 18F/beta.foia.gov.git denied to jhuang0427.
I am working more

**Comment by jhuang0427** [comment]
@adborden @brockfanning Sorry, I forgot to fork the repository
