### ISSUE TITLE
a RESTful HTTPS API spec

### ISSUE THREAD

**Issue by pkarman** [usdoj/foia.gov#32]
As an agency that uses a case management system, in order to receive requests from the portal, I need a RESTful HTTPS API spec and request payload schema that I can use to implement.

- [ ] status code definitions
- [ ] example of API request (ex: cURL request)
- [ ] example of API response
- [ ] security section describing implications of receiving request data

note: some of this is already available in the spec in this repo

**Comment by leahbannon** [comment]
- [ ] status code definitions
- [ ] example of API request
- [ ] example of API response
- [ ] cURL request example 

note: some of this is already available in the spec in this repo

**Comment by bsweger** [comment]
Have a very rough draft going here: https://github.com/18F/foia/blob/sample-api-spec/sample-http.md
