### ISSUE TITLE
Drupal Training/Documentation

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#326]
As the O&M team, in order to maintain the portal post-launch, I need training, documentation, and resources (to provide users). 
 
Deliverable | Description | Audience
-- | -- | --
Training: Portal agency admin user training | Overview of portal architecture and use | OIP, CWS
Demo: Drupal 8 administrator walkthrough | Overview of Drupal 8 for admins | CWS
Training: API Knowledge Transfer | Overview of API and how to onboard agencies | CWS
Documentation: General system maintenance | Overview of what an admin should know for day to day management of the portal | OIP, CWS
Documentation: System architecture | Outline content types, taxonomy, user groups/permissions, etc. used | CWS
Documentation: User accounts | How Agency Administrators create accounts for Agency Managers in Drupal | AM
Documentation: Content Management | How to modify agency and component records including forms | AM, OIP, CWS
Documentation: Agencies: Receiving FOIA Requests | Managing the method by which an agency receives FOIA requests | OIP, CWS

## Acceptance criteria

- [x] Demo: Drupal 8 administrator walk through
- [x]  Training: Portal agency admin user training
- [x]  Training: API Knowledge Transfer
- [x]  Documentation: General system maintenance 
- [x]  Documentation: System architecture 
- [x]  Documentation: User accounts
- [x]  Documentation: Content Management
- [x]  Documentation: Agencies: Receiving FOIA Requests

### Folder containing working copies of documents

https://drive.google.com/drive/folders/1StJXXotzqFz2altzgmpza7-frnTWMwqE

**Comment by dangur** [comment]
@kristusacquia @malikkotob do you know for
```
Documentation: General system maintenance | Overview of what an admin should know for day to day management of the portal | OIP, CWS
```
is that for an `Administrator` role or `Agency Administrator` role?

**Comment by dangur** [comment]
@malikkotob For the `General system maintenance` deliverable of an `Overview of what an admin should know for day to day management`. Do we know if that is the `Administrator` or `Agency Administrator` role?

**Comment by kristusacquia** [comment]
@dangur We need something at an Admin level that describes how they should maintain the portal on a daily, weekly, monthly, quarterly basis. It was a question that came from OIP.  I am assuming that only a few people will have the Agency Admin role, and that role focuses on managing forms, users, accounts, etc.. If that assumption is correct, their tasks are covered in other documentation already so we're ok to focus this on System/Portal Admin stuff. Hope I'm making sense.
