### ISSUE TITLE
Form help text contains escaped html

### ISSUE THREAD

**Issue by adborden** [usdoj/foia.gov#328]
![screenshot from 2017-11-06 09-53-18](https://user-images.githubusercontent.com/509703/32455867-7cd95480-c2d8-11e7-8461-bac455759f94.png)

## Steps to reproduce the behavior

1. http://foiafrontdev.prod.acquia-sites.com/request/agency-component/8216158f-8089-431d-b866-dc334e8d4758/
1.
1.

**Comment by adborden** [comment]
@malikkotob as far as I know, this is the only text coming from the API that is escaped. What's the best plan here? Should we just treat it as raw html? I'm curious about agency descriptions as well, should those be treated as raw html? I hadn't noticed the escaping issue anywhere else from the API.

**Comment by malikkotob** [comment]
@adborden I think there are other places that are sending things over as escaped. It's a result of fields that use rich text editing experiences in the admin forms. I think treating these as raw html is the way to go. Another example where I would expect to see that is the description field on the component.

**Comment by adborden** [comment]
On Mon, 2017-11-06 at 10:21 -0800, malikkotob <notifications@github.com> wrote:
> @adborden I think there are other places that are sending things over as escaped. It's a result of fields that use rich text editing experiences in the admin forms. I think treating these as raw html is the way to go. Another example where I would expect to see that is the description field on the component.

Okay, so if I see a text field that has a 'rich_text' as the format, I
should assume it's safe to render that as raw html?

--
Aaron D Borden
Human and Hacker

**Comment by malikkotob** [comment]
@adborden yes. I believe for all non-webform element pieces that should work. For the webform elements, it does not provide a similar format indicator. With that being said, the `#help` key, as you've discovered, as well as the `#description` key (not currently in use) would be treated the same.
