### ISSUE TITLE
Build a public API to expose a machine-readable copy of an agency's metadata

### ISSUE THREAD

**Issue by bsweger** [usdoj/foia.gov#33]
Issue #16 will define the data that we need to collect from FOIA offices to create their metadata (which will them be used to power the process of making requests).

This issue is to create the API based on those findings.

- [x] The API delivers a machine-readable copy of an [agency's metadata](https://github.com/18F/foia-recommendations/blob/master/schemas.md#agency-metadata-file)
- [ ] The response follows our [defined schema](https://github.com/18F/foia-recommendations/blob/master/schemas.md#schema)
- [x] The API is publicly accessible
- [ ] Configure behind api.data.gov (api umbrella)

**Comment by adborden** [comment]
Based on the conversation today, do we want to start with a read-only API and go from there, or do we want to include a write API right from the start?

**Comment by bsweger** [comment]
@adborden Good question. Since the need for a write API is very TBD, I think it makes sense to be explicit that this story is for a read-only API. That said, I'm unsure of the Drupal dev effort that would be involved in layering in the write capability should surface as a requirement based on team's research.

@ba66e77 @malikkotob what do you think?

**Comment by ba66e77** [comment]
@bsweger, I understood that a write API was not under consideration and that editing to entities would be done through the Drupal admin UI.

**Comment by malikkotob** [comment]
@bsweger, @adborden, based on our conversation yesterday during standup, mind if we change the title of this issue to something along the lines of: "Build a public API to expose a machine-readable copy of a FOIA office's metadata"?

**Comment by adborden** [comment]
@malikkotob Sure thing. I just updated it with a minor tweak of your copy based on the language discussion today. We are still aiming for agency-level metadata, not the agency component (FOIA Office). Feel free to tweak it as you see fit :)

**Comment by adborden** [comment]
I just added links to schemas.md to the AC so it's clear that the API should follow this format.

**Comment by malikkotob** [comment]
Sample metadata for DOJ attached:
[DOJ_Metadata.txt](https://github.com/18F/beta.foia.gov/files/1294578/DOJ_Metadata.txt)

Once this ticket is code reviewed and deployed to our staging environment, the following url can be hit to retrieve metadata for the different agencies:
```
/jsonapi/agency_components?_format=api_json&filter[agency][condition][path]=agency&filter[agency][condition][value]=696&include=agency,foia_officers,public_liaisons,paper_receiver,service_centers,request_form&fields[webform]=elements
```

The value `696` in the path above is the id given in Drupal for the Department of Justice taxonomy term. An approach should be discussed for how the frontend will retrieve all of these internal ids (will they be hardcoded? will there be an additional endpoint to fetch them? etc.)

As discussed with Aaron, the metadata was generated by the `JSON API` library, and as such, takes on a different format than the one referenced in `schemas.md`. Additionally, a [separate ticket](#111) was created for the `api.data.gov` piece, since we do not have domain names decided on or setup.

**Comment by malikkotob** [comment]
@adborden you should now be able to hit this API directly by visiting:

http://foiastg.prod.acquia-sites.com/jsonapi/agency_components?_format=api_json&filter[agency][condition][path]=agency&filter[agency][condition][value]=**<internal_drupal_agency_id>**&include=agency,foia_officers,public_liaisons,paper_receiver,service_centers,request_form&fields[webform]=elements

Some agency ids to test:
696 - DOJ
821 - GSA
1066 - State

**Comment by malikkotob** [comment]
@adborden just discovered that JSON API's filtering capabilities are better than I thought, so there's no need to filter on the internal ID Drupal gives to the agency. Here's an example filtering on abbreviation for the Department of State (DOS), which is cleaner:
http://foiastg.prod.acquia-sites.com/jsonapi/agency_components?_format=api_json&filter[agency.abbreviation][value]=DOS&include=agency,foia_officers,public_liaisons,paper_receiver,service_centers,request_form&fields[webform]=elements

**Comment by adborden** [comment]
Hey, sorry I'm a little late getting back to you on this. I think I'll learn a lot when I actually start playing with it as part of https://github.com/18F/beta.foia.gov/issues/116. My hunch is that even though a developer can choose to filter it, what is the point of having the internal ID? When we write the documentation for this API, what will the docs say about using these fields?
