### ISSUE TITLE
agency GUI content research

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#35]
- [x] review 90% list
- [x] research form fields on 90% list that have already been built/tested by 18F/USDS
- [x] research existent content that agencies use for FOIA form content that match the 90%

**Comment by RyanSibley** [comment]
90 percent list: https://docs.google.com/a/gsa.gov/spreadsheets/d/1eJ1Bzug6Q_jtXdHtzpStIcEHva9-QWCbvhw0GjOrAw8/edit?usp=sharing

**Comment by vz3** [comment]
Editing criteria to add "capture 10% questions"

**Comment by RyanSibley** [comment]
The edited list of 90 percent fields is found here: https://docs.google.com/spreadsheets/d/1eJ1Bzug6Q_jtXdHtzpStIcEHva9-QWCbvhw0GjOrAw8/edit?pli=1#gid=0

 

Examples of content already produced by agencies that can help as we put together explanatory content is in progress here: 

https://drive.google.com/drive/folders/0B6JwOhTn6nKVaWRvRXZrTnZGR28

**Comment by vz3** [comment]
Moving this to review
