### ISSUE TITLE
Implement copy in agency tab  of side bar

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#350]
OIP is working on copy for the agency tab for the side bar. When they send it over I'll implement it. 

<img width="667" alt="screen shot 2017-11-07 at 12 19 06 pm" src="https://user-images.githubusercontent.com/1151139/32507600-e09a976c-c3b5-11e7-87cb-e6a32b2eaf57.png">

**Comment by hbillings** [comment]
We're removing these instead.
