### ISSUE TITLE
Fix links to quarterly and annual data

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#351]
Currently the links are swapped. Work with Aaron or Heather and Matt to make sure this is sorted out.

**Comment by adborden** [comment]
I believe this was fixed in https://github.com/18F/beta.foia.gov/pull/311 and merged this morning. Can you confirm? http://foiafrontdev.prod.acquia-sites.com/

**Comment by RyanSibley** [comment]
I'm pretty sure this is right, but I'll ask OIP to confirm as well.
