### ISSUE TITLE
Add more glossary edits and remove one term

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#352]
OIP is working on edits to the following terms: 
<img width="683" alt="screen shot 2017-11-07 at 12 21 51 pm" src="https://user-images.githubusercontent.com/1151139/32507738-500f1eb0-c3b6-11e7-95c0-7cecbecc86cb.png">

When Matt is done with the edits, I'll incorporate them into the glossary

**Comment by adborden** [comment]
I _think_ these edits are in, but maybe check with @RyanSibley. Assigning to @leahbannon to follow up ❤️

**Comment by leahbannon** [comment]
Confirmed this is done
