### ISSUE TITLE
build mockup of contact updater form

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#37]
- [ ] design basic page if agency has no data
- [ ] design page if agency has data to edit (maybe use GSA real data for example)
- [ ] talk to drupal dev to understand LOE implications (tactical time?)

**Comment by ba66e77** [comment]
It would be helpful on this if one of our Drupal engineers can work with you.  Some approaches may be lower LOE to implement than others.

**Comment by adborden** [comment]
I think the fist part of this has been started. The issue to implement the styles for this is covered by https://github.com/18F/foia/issues/69.

**Comment by AvivaOskow** [comment]
**(Old)**

![agency info update form](https://user-images.githubusercontent.com/21244661/30388862-1b9d1676-987f-11e7-85a9-bf6f250d7377.jpg)
