### ISSUE TITLE
remove "where to make a FOIA request"

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#370]
remove from:
- [ ] header dropdown
- [ ] legacy page menu

**Comment by adborden** [comment]
Anyone who bookmarked this link should be taken to the agency finder right? That's an anchor link https://dev-www.foia.gov/#agency-search. My gut says this isn't the most intuitive experience but that's what we'll do for now.

**Comment by leahbannon** [comment]
sgtm
