### ISSUE TITLE
Open source the Drupal portion of the project

### ISSUE THREAD

**Issue by bsweger** [usdoj/foia.gov#38]
To make sure the team is working transparently:

- [x] GitHub repo for existing Drupal code is public (either in DOJ org or 18F org)
- [x] All team members have read/write access
- [x] Repo contains instructions for standing up a local dev environment
- [x] rename repo to FOIA API
- [x] add slack integration to #foia-partners

**Comment by adborden** [comment]
@leahbannon I added a task to add the repo as a slack integration.

**Comment by leahbannon** [comment]
@malikkotob could you rename the DOJ FOIA repo to "FOIA API"? Do you see any issues with that?

**Comment by malikkotob** [comment]
@leahbannon no issues on my end, but I don't have the rights to do that. I believe Brock from DOJ may be the one with the right permissions (he's the one who open sourced the repo).

**Comment by adborden** [comment]
@brockfanning ^

**Comment by brockfanning** [comment]
@malikkotob @leahbannon @adborden To make sure I understand right, are you asking me to edit the "Description" of https://github.com/usdoj/foia from "FOIA 2.0 (DOJ/Acquia)" to "FOIA API"? Or are you asking me to change the repository name from "foia" to something like "foia-api", which would change the URL to https://github.com/usdoj/foia-api?

**Comment by leahbannon** [comment]
@brockfanning We'd like the repo name changed from "foia" to "foia-api" - thanks!

**Comment by brockfanning** [comment]
Ok, that's done.

**Comment by leahbannon** [comment]
Request for slack integration submitted.
