### ISSUE TITLE
Miscellaneous Launch Prep Tasks

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#393]
## Acceptance criteria

*Malik*
- [x] Send SAML metadata to Max.gov with new domain names
- [x] Setup acquia_connector module
- [ ] Setup Memcache
- [x] Enable caching
- [x] Setup api.data.gov to only route requests to origin if they are going to /api
- [x] Block access to /admin, /node, and /user paths

*Dan*
- [x] Disable watchdog (`dblog`) and verify `syslog` is enabled
- [x] Verify error reporting to screen is disabled (php errors - only admins should be able to see these)
- [x] Prevent search engines from indexing pages for backstage domains
    - admin.foia.gov
    - api2.foia.gov
- [x] Disable /search
- [x] Test SAML login once Max.gov is updated with new metadata

*TAM*
- [x] Setup VCL

## Functional Review

- [ ] Go to /admin/modules
- [ ] See that Database Logging module checkbox is unchecked
- [ ] See that Syslog module checkbox is unchecked
- [ ] Go to /admin/config/development/logging
- [ ] See that “None” radio button is selected under “Error messages to display”
- [ ] Go to /search
- [ ] See page not found message

## Developer Review

Code review [PR 108](https://github.com/usdoj/foia-api/pull/108)

### Setup

- [ ] memcache patch for blt `composer install`
- [ ] pull down new database `blt sync`
- [ ] Import config `drush cim`
- [ ] Uninstall Simple SAML PHP Auth module `drush pmu simplesamlphp_auth`

#### Automated tests

- [ ] Run configuration automated tests `blt tests:behat -D behat.paths=Configuration.feature`

#### Access blocked to /admin, /node, and /user paths

If testing on local, see that the following commands return 403 forbidden:
curl -H "host:api2.foia.gov" http://local.dojfoia.gov/admin
curl -H "host:api2.foia.gov" http://local.dojfoia.gov/node/1
curl -H "host:api2.foia.gov" http://local.dojfoia.gov/user
If testing on Acquia Cloud, the commands are as follows:
curl -H "host:api2.foia.gov" http://dev-admin.foia.gov/admin
curl -H "host:api2.foia.gov" http://dev-admin.foia.gov/node/1
curl -H "host:api2.foia.gov" http://dev-admin.foia.gov/user
(Swap stg for dev above if on Stage)

**Comment by kristusacquia** [comment]
Removed Memcache task because it is not launching critical.
