### ISSUE TITLE
Implement a redirect to the agency search box on the homepage

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#395]
As a [user], in order to find the place on FOIA.gov that contains up-to-date contact information, I need to be redirected from https://www.foia.gov/report-makerequest.html to the agency search box on www.FOIA.gov.

The idea here is that people might go to the old location containing contact information on the site that is no longer being updated. At the moment, the information is still good, but it will be useless in the near future. When that happens, putting an automatic redirect in place would be helpful, especially considering some folks might have the old page bookmarked. Currently, https://www.foia.gov/report-makerequest.html has a banner telling people that the content on that page will no longer be updated. This task is being iceboxed until the FY 2019 team begins work.

**Comment by adborden** [comment]
I think it is already done as per https://github.com/18F/beta.foia.gov/issues/370
Going to https://dev-www.foia.gov/report-makerequest.html redirects you.
