### ISSUE TITLE
Conduct content audit of foia.gov

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#4]

**Comment by adborden** [comment]
Here's a [crawl of www.foia.gov](https://gist.github.com/adborden/646729607fab65f940a77246e00f92a2).

You can download the pages for inspection https://drive.google.com/a/gsa.gov/file/d/0B5EC5Q83gYbob1FDY2diYmROYVk/view?usp=sharing

**Comment by RyanSibley** [comment]
Classification started here:

https://docs.google.com/spreadsheets/d/12LdK_BjmzGuvTVzcNxicui_Zzo8BOLkN-2dAf9XBWGo/edit#gid=0

There are 4 buckets:

- Informational (articles, press releases, etc)

- Resource (instructions for making a request, FOIA contacts, etc.)

- Contextual (FOIA history, FOIA reports, USC, ammendments to the law)

- Metadata/developer tools
