### ISSUE TITLE
Build Agency in Drupal

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#40]
Create an 'Agency' taxonomy vocabulary in Drupal. Each term in the vocabulary will be an agency (e.g. Department of Justice). The fields on the Agency will come from the data modeling activity in #16.

**Acceptance Criteria**
- [x] Rename the existing Department taxonomy to Agency
- [x] Fields to be included on the Agency:
   
    - name (text field)
    - abbreviation (short text, ~5 characters)
    -  usa_id (int)
    - seal (image upload)
    - agency description (text area)

## UAT

**Test**: Create an agency
**Applicable roles**: admin, agency administrator

- [ ] Login via MAX.gov at https://dev-admin.foia.gov/user/login
- [ ] Navigate to https://dev-admin.foia.gov/admin/structure/taxonomy/manage/agency/add
- [ ] Fill out the fields as appropriate and click "Save"
- [ ] Verify you receive a message that indicates successful creation of the agency
- [ ] Click on the link in the message (it should take you to the agency you created)
- [ ] Take note of the URL as you will need it for the next test

**Test**: Delete an agency
**Applicable roles**: admin, agency administrator

- [ ] If needed, login via MAX.gov at https://dev-admin.foia.gov/user/login
- [ ] Navigate to the agency that was newly added in the previous step
- [ ] Click the "Edit" tab on the agency
- [ ] Scroll down to the bottom of the agency
- [ ] Click the "Delete" link
- [ ] Click the "Delete" button on the page you are redirected to
- [ ] Verify you receive a message indicating the agency has been deleted

**Test**: Edit an agency
**Applicable roles**: admin, agency administrator, agency manager

- [ ] Login via MAX.gov at https://dev-admin.foia.gov/user/login
- [ ] Navigate to https://dev-admin.foia.gov/taxonomy/term/1276
- [ ] Verify that you see a description for the DOJ along with an abbreviation
- [ ] Click the edit tab at the top of the agency
- [ ] Verify that the following fields are populated:
    - [ ] Name
    - [ ] Abbreviation
    - [ ] Description
- [ ] Make a small change to one of the fields on the agency and click "Save"

**Comment by ba66e77** [comment]
I've pulled the fields from #16 into the description for this ticket.  Unblocking it.

**Comment by malikkotob** [comment]
Ready for review - assigned to @ba66e77.

**Comment by gsolomon123** [comment]
I am able to create, delete, and edit an agency successfully.  This functions as expected.
