### ISSUE TITLE
Update Request Form template to include universal form fields

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#42]
Update the request form template to house the 90% of universal FOIA request form fields identified in #16.

**Acceptance Criteria**
- [x] The [universal form fields identified in #16](https://drive.google.com/file/d/0B4JtVmWTTdQEU0lraVdZNVB2d0k/view) are on the request form template

## UAT

**Test**: Create a new request form
**Applicable roles**: admin, agency administrator

- [ ] Login via MAX.gov at https://dev-admin.foia.gov/user/login
- [ ] Navigate to https://dev-admin.foia.gov/admin/structure/webform
- [ ] Click the "Add Webform" button
- [ ] Enter a title for the new form (e.g. Test FOIA Request Form)
- [ ] Verify the "Use FOIA Agency template" checkbox is checked
- [ ] Click "Save"
- [ ] Verify that you are redirected to a page with all of the fields on the newly created webform
- [ ] Verify that the only field with the "required" box checked is the `Your request` field

**Test**: Edit a request form
**Applicable roles**: admin, agency administrator
- [ ] If needed, login via MAX.gov at https://dev-admin.foia.gov/user/login
- [ ] Navigate to https://dev-admin.foia.gov/admin/structure/webform
- [ ] Click on the title of the form that was created in the previous test
- [ ] Click on the "Build" tab
- [ ] Click on the "First name" field
- [ ] Enter help text and click "Save"
- [ ] Verify you receive a message indicating the field was successfully updated

**Comment by adborden** [comment]
Just wanted to call out this comment https://github.com/18F/foia/issues/16#issuecomment-320291217

> From a data modeling perspective, we might want to capture the 90% fields as a separate entity from the request form entity. As mentioned in #16 (comment), there might be some research that would require us to have some customization of the 90% fields and that data would land in the request form entity. As an example, in our experience map/backstage demo, there was a possibility that a FOIA officer could choose one of three options to render the name fields (single field, first/last, or prefix/first/last/suffix). That kind of thing would be captured in the request form entity.

I'm not sure of the drupal implications, but it sounds like the "request form template" kind of acts as a separate entity from the request form entity without being an explicit entity. Is that right?

**Comment by ba66e77** [comment]
@adborden, that's correct.  The template defines fields that can auto-populate the form being created.

**Comment by ba66e77** [comment]
It sounds like there are still enough questions about exactly what we're putting into the template (and form creation in general) that we should put this in the icebox for now.

**Comment by malikkotob** [comment]
@adborden Note that the captcha element was not implemented here, as that piece seems like it will only exist on the request form generated for the frontend. If that's not the case, we can discuss whether or not you had a different approach in mind.

**Comment by adborden** [comment]
:+1: Let's skip the captcha for now and return if it's necessary.

**Comment by dangur** [comment]
There is an outstanding PR, which is the automated testing for this https://github.com/usdoj/foia/pull/61.

**Comment by dangur** [comment]
### Developer Review
[ ] Review [PR 61|https://github.com/usdoj/foia-api/pull/61]
[ ] Check out <doj-42-dg>
[ ] Run phpunit tests from inside the VM <vagrant ssh> then <blt tests:phpunit>
[ ] See OK (1 test, 6 assertions)

**Comment by Tom-Camp** [comment]
Code review pass

**Comment by malikkotob** [comment]
All set here.

**Comment by gsolomon123** [comment]
Create a new request form - works as expected; form successfully created
Edit form - successfully edited and message received that first name was updated; saved form and message received that form elements were updated.
