### ISSUE TITLE
Send FOIA Request Submission via email

### ISSUE THREAD

**Issue by ba66e77** [usdoj/foia.gov#43]
As an Agency that receives requests via email, I want a well-formatted email containing the request so we can receive requests from the portal and enter them quickly into our spreadsheet

**Comment by adborden** [comment]
Just jotting down some thoughts before Sprint Planning next week. Converting it to an epic because I think there are a few pieces to this. I believe this will include some design work, some API work, and some wrangling of a third-party email service.

**Comment by ba66e77** [comment]
d'oh.  Reopening. Closed it inadvertently.

**Comment by leahbannon** [comment]
closing out epics
