### ISSUE TITLE
Modify Request Form Help Text 

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#433]
As a product owner, in order to ensure that users are able to easily use the request form, I need to improve the help text language.

Text changes are here: https://docs.google.com/a/acquia.com/document/d/1ONYd4EZwdLbwLQ750FrGGFKoAunRH-ay_Jaks8VYllQ/edit?usp=sharing

## Acceptance criteria

- [x] Help text matches the changes in the document attached.

## Functional Review

- [x] Navigate to https://dev-www.foia.gov/request/agency-component/8216158f-8089-431d-b866-dc334e8d4758/
- [x] Verify the help text by the "Upload additional documentation" field is no longer there
- [x] Verify the "What type of requester are you?" dropdown has the following options:
```
Representative of the news media
Educational Institution
Non-commercial scientific institution
Commercial-use requester
All other requester
```

- [x] Verify the help text for the "Fee waiver" field is no longer there
- [x] Verify the help text for the "Fee waiver justification" field is:
> Leave this blank if you are not requesting a fee waiver. When making a request for a fee waiver you must explain how your request meets the fee waiver standard described above.

- [x] Verify the help text for the "Justification for expedited processing" field is:
> Leave this blank if you are not requesting expedited processing. When making a request for expedited processing you must explain how your request meets one of the expedition standards described above.

## Developer Review

- [x] Review [PR 109](https://github.com/usdoj/foia-api/pull/109)

*Setup*
- [x] Run `blt sync`
- [x] Checkout `doj-433-mk` locally
- [x] Import config: `drush cim`
- [x] Clear caches: `drush cr`

*Testing*
- [x] Perform functional review
- [x] Create a new webform based off of the template and verify that it is created with the latest changes verified in functional review
- [x] Verify all automated tests pass

## UAT

- [ ] Navigate to https://dev-www.foia.gov/request/agency-component/8216158f-8089-431d-b866-dc334e8d4758/
- [ ] Verify the help text by the "Upload additional documentation" field is no longer there
- [ ] Verify the "What type of requester are you?" dropdown has the following options:
```
Representative of the news media
Educational Institution
Non-commercial scientific institution
Commercial-use requester
All other requester
```

- [ ] Verify the help text for the "Fee waiver" field is no longer there
- [ ] Verify the help text for the "Fee waiver justification" field is:
> Leave this blank if you are not requesting a fee waiver. When making a request for a fee waiver you must explain how your request meets the fee waiver standard described above.

- [ ] Verify the help text for the "Justification for expedited processing" field is:
> Leave this blank if you are not requesting expedited processing. When making a request for expedited processing you must explain how your request meets one of the expedition standards described above.

**Comment by malikkotob** [comment]
Merged into `develop`.
