### ISSUE TITLE
New User Notifications

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#437]
As a security analyst, in order to ensure that new accounts are not created by unauthorized users )or without my knowledge), I need to ensure that site administrators are notified whenever new accounts are created.

POAM: The FOIA Portal does not notify personnel of account creation. The FOIA application logs when new accounts are created but no notification is sent out.

## Requirement

- [x] Using a Drupal module, create the ability to notify a specified email address when a new portal user account is created. 
- [x] For MVP the email address will not be managed using the Drupal admin interface.
- [x] Configure notifications such that a distribution list or single email account can be notified.

## Acceptance criteria

- [x] When a new portal user account is created, an email is sent to the specified email account notifying that an account was created.

## Functional review
- [x] Go to `/admin/config/workflow/rules/reactions/edit/new_user_notification/edit/d1bd3ce9-1e63-443a-8d64-f4d5bdaaad66`
- [x] Enter your email address for the `SEND TO Value`
- [x] Press the `Save` button
- [x] Go to `admin/people/create`
- [x] Enter a username, password, and confirm the password
- [x] Press the `Create new account` button
- [x] See the following success messages: `Created a new user account for A Test User. No email has been sent.`
- [x] Go to "admin/reports/dblog"
- [x] See the message `Successfully sent email to _your.email@address.com_`

### Code review
- [x] Code review [PR 111](https://github.com/usdoj/foia-api/pull/111)

### Setup
- [x] Deploy `doj-437-dg` to dev
- [x] Import config `drush cim`
- [x] Reload cache `drush cr`

### Automated tests
- [x] Run all automated tests to see that they pass

### Functional review
- [x] Go through the functional review steps above

**Comment by malikkotob** [comment]
Merged into `develop`.
