### ISSUE TITLE
Session Locking

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#438]
#As a security analyst, in order to ensure that secure data or PII are not exposed when a session is left open and inactive,  I need to ensure that the system locks after a user is inactive for 15 minutes.

POAM: The application does not currently have any session locking mechanism.

## Requirements:  

- [x] Log a user out of the system if they are inactive for 15 minutes.
- [x] Redirect the user's browser to a specified URL after a user has been inactive for 15 minutes.

## Acceptance criteria

- [x] A user who has been inactive for 15 minutes is locked out of the system and redirected to the correct URL.

## UAT
**Relevant roles**: admin, agency administrator, agency manager

- [ ] Visit https://dev-admin.foia.gov/user/login
- [ ] Login using MAX.gov by clicking on the "Login via MAX.gov" link
- [ ] Verify that after 15 minutes of inactivity you get a warning message that your session is about to expire and that if you do not respond you are logged out of Drupal.

## Developer review
- [x] Review PR https://github.com/usdoj/foia-api/pull/110

- [x] Build and deploy the PR to a cloud environment where Max.gov authentication is in place
- [x] Run `drush cim` to enable the autologout module and set configuration
- [x] Log in via max.gov
- [x] Verify that after 15 minutes of inactivity your get a warning message that your session is about to expire and that if you do not respond you are logged out of Drupal.

**Comment by malikkotob** [comment]
Merged into `develop`.

**Comment by gsolomon123** [comment]
This functions as expected.
