### ISSUE TITLE
Handle or disable webform submissions via Drupal UI

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#445]
Component request forms can be submitted in Drupal directly by visiting /form/<form-id> for the component's form. This would allow someone to submit a request with more than 20MB worth of attachments. If preventing FOIA requests from being submitted in this manner is desired, we can explore solutions related to blocking paths beginning with /form, or we can simply discard requests that did not come through api.data.gov.

## Acceptance criteria

- [ ] 
- [ ]
- [ ]

**Comment by brockfanning** [comment]
This was completed.
