### ISSUE TITLE
Add Confirmation ID to Email and API Transmissions

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#446]
As a requester, in order to have a referencable ID for my submission which can be used in communication with components, I need the confirmation ID I receive to also be sent to agency components.

## Acceptance criteria

- [x]  When a FOIA request is transmitted via email, the submission ID is included in a `Confirmation ID` field
- [x]  When a FOIA request is transmitted via API, the submission ID is included in a `confirmation_id` field

We may also want to change the API spec.

### Email

- [x] Go to /admin/content
- [x] Find the `Office of Information Policy` agency component
- [x] Click the `Edit` button in that row
- [x] In the `PORTAL SUBMISSION OPTIONS` fieldset
- [x] Set the `Portal Submission Format` to `Email`
- [x] Enter your email address in the `Submission Email` field
- [x] Set the `Request Submission Form` field dropdown selector to `Test Form`
- [x] Press the `Save` button
- [x] Go to /form/test-form
- [x] Enter some text in the required `Your request` field
- [x] Press the `Submit` button
- [x] Ask Dan or Malik to process the foia_submissions queue `drush queue-run foia_submissions`
- [x] Go to `/admin/content/foia-requests`
- [x] See that the request you just created has a status of `Submitted to component`
- [x] Check your email and see that the confirmation id is included in the email from the FOIA system

### API

- [x] Go to /admin/content
- [x] Find the `Office of Information Policy` agency component
- [x] Click the `Edit` button in that row
- [x] In the `PORTAL SUBMISSION OPTIONS` fieldset
- [x] Set the `Portal Submission Format` to `API`
- [x] Enter `https://usdoj.gov` in the `Submission API URL` field
- [x] Set the `Request Submission Form` field dropdown selector to `Test Form`
- [x] Press the `Save` button
- [x] Go to /form/test-form
- [x] Enter some text in the required `Your request` field
- [x] Press the `Submit` button
- [x] Ask Dan or Malik to process the foia_submissions queue `drush queue-run foia_submissions`
- [x] Go to `/admin/content/foia-requests`
- [x] See that the request you just created has a status of `Failed submission to component`
- [x] See that the error message is `Did not receive JSON response from component.`

## Developer review

- [x] Review [PR 117](https://github.com/usdoj/foia-api/pull/117)

### Setup

- [x] Import database `blt sync`
- [x] Configure email sending

### Testing

- [x] Complete functional review steps above
- [x] Run automated tests and see that they pass

**Comment by malikkotob** [comment]
@dangur Overall this looks good, but placing back in dev to address some comments in the PR.

**Comment by malikkotob** [comment]
Passes code review, moving along to UAT.

**Comment by malikkotob** [comment]
Merged into `develop`.
