### ISSUE TITLE
Upgrade to PHP 7

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#447]
As a Portal Administrator, in order to ensure that the system is using the most recent release of PHO  I need to upgrade to version 7.

## Acceptance criteria

[ ] Before starting this work, check if https://www.drupal.org/project/simplesamlphp_auth/issues/2925106 is resolved
[ ] Upgrade local VM setup to use PHP 7
[ ] Confirm that PHP 7 is installed with no adverse impact to the application

**Comment by brockfanning** [comment]
This was completed.
