### ISSUE TITLE
Security review hardening

### ISSUE THREAD

**Issue by dangur** [usdoj/foia.gov#448]
Security review revealed these vulnerabilities:
- [x] Common username for user 1
- [x] No validation code in webform submission resource
- [x] https isn't being forced on *.acquia.com domains using self-signed cert
- [x] Contact form is visible
- [x] Migration modules are enabled
- [x] Unnecessary core views are enabled

## Acceptance criteria

- [x] Username for user 1 is changed to an uncommon one
- [x] Validation code is added to webform submission resource
- [x] https is being forced on *.acquia.com domains using self-signed cert
- [x] Contact form is visible
- [x] Migration modules are disabled
- [x] Unnecessary core views are disabled

## Functional review

- [x] Visit http://foiastg.prod.acquia-sites.com/user/1
- [x] See that the username is not `admin`
- [x] Visit http://foiauat.prod.acquia-sites.com/
- [x] See that you are redirected to https://foiauat.prod.acquia-sites.com/
- [x] Note that you may get an `Invalid Certificate Authority Error`, which is ok
- [x] Visit /contact
- [x] See a `Page not found` error message
- [x] Visit /admin/modules
- [x] Type `contact` in the filter box
- [x] See that `Contact`, `Contact Form`, & `Contact storage` modules are not enabled
- [x] Type `migrate` in the filter box
- [x] See that `Migrate`, `Migrate Plus`, & `Migrate Tools` modules are not enabled

## Developer review

- [x] Code review [PR 135](https://github.com/usdoj/foia-api/pull/135)

### Setup
- [x] Checkout branch `doj-448-dg-mk`
- [x] Refresh database `blt sync`
- [x] Import config `drush cim`
- [x] Classify existing files into new file entity types `drush cron`
- [x] Reload caches `drush cr`
- [x] Unpublish the OIP component (only do this step locally)

### Tests
- [x] Locally, submit a FOIA request via API to the OIP component
- [x] Verify the response is:
```
{
    "errors": "Invalid form ID. Check the agency metadata for the latest form information for the desired agency component."
}
```

- [x] Deploy code to uat environment
- [x] Complete functional review steps
- [x] Run behat and phpunit tests locally: `blt tests`
- [x] See that all automated tests succeed

**Comment by Tom-Camp** [comment]
PR: https://github.com/usdoj/foia-api/pull/131

**Comment by malikkotob** [comment]
Merged into `develop`.
