### ISSUE TITLE
Create a diagram to model the flow of agency metadata and request data

### ISSUE THREAD

**Issue by bsweger** [usdoj/foia.gov#45]
Adding this because I'm personally wanting some visual clarity about how data and what data flows through the journey map that we talked through.

- [ ] diagram includes the data flow process about the platform that serves agency component metadata (_i.e._, how agency component metadata is captured and how it gets to a person who is requesting the metadata)
- [ ] diagram shows origin of all pieces of the agency component metadata (_e.g._, an agency, an agency component, the 90% list)
- [ ] diagram shows the actors who create and update data

**Comment by RyanSibley** [comment]
I'm adding this diagram that @adborden created to illustrate the request submission flow. To keep everything straight in my mind it would be nice to see how the two diagrams relate to each other.

https://github.com/18F/foia-recommendations/blob/master/img/request-submission-platform.png

**Comment by bsweger** [comment]
Thanks for posting that @RyanSibley. For the diagram I'm proposing here, I'd like to take a deep dive into the first two steps of the chart above (and even think about the steps that come before: how does the agency metadata get there?).

My original acceptance criteria didn't reflect that intent very well, so I've revised them with help from @adborden. Does this make more sense? 

I get the feeling that everyone understands how this will work conceptually but that once we dig deeper, we're not all aligned on what data is coming from where (and from who) and what it needs to look like from the perspective of someone who wants to see/use the agency component metadata.

Some of these things we don't know yet or will change, but my hunch is that having something on paper to start with will be helpful.

**Comment by bsweger** [comment]
A draft I've been noodling on. I know this isn't quite right, especially WRT the origin of the annual request time stats, but it's something we can discuss and respond to: https://docs.google.com/drawings/d/176plwHal8PZ060UUAKYM2KLMaEOcGbodzrUKEfyCC8Y/edit

Another question is about what, if any, updates to individual agency component metadata pieces will need to be reviewed and approved by OIP.

**Comment by bsweger** [comment]
Because this diagram now has a dual purpose use, we "forked" the original copy and moved it to the security/ATO folder: https://drive.google.com/open?id=1TFArNY2LNQIMTOHpYP3CU8F_jZuHroFegJyYcslaA9A

To avoid the confusion of multiple copies floating around I removed the original draft from the shared drive (though I still have it for reference).

**Comment by adborden** [comment]
I'm going to add a screen shot to the foia-api repo.
