### ISSUE TITLE
Update request creation logic

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#453]
As a security analyst, to ensure that files transmitted from the portal do not contain viruses, I need a file scanning process that provides affirmative confirmation that infected files have been stripped prior to transmission.

Task: Update request creation logic to set conditional request status based on presence of uploaded files

## Acceptance criteria

- [x] Requests submitted with at least one attachment receive the status of `Pending virus scan`
- [x] Requests submitted with zero attachments continue to receive the status of `Queued for submission`

## Functional review

- [x] Go to `/form/test-form`
- [x] Enter text in the required `Your request` field
- [x] Do _not_ attach a file
- [x] Press the Submit button
- [x] Click the `Back to form` button
- [x] Enter text in the required `Your request` field
- [x] _Do_ attach at least one file (total file sizes should be < 20MB)
- [x] Press the Submit button
- [x] Click the `Content` link in the toolbar
- [x] Click the `FOIA Requests` tab
- [x] See that your first submission (which should appear second in the list) has a status of `Queued for submission`
- [x] See that your second submission (which should appear first in the list) has a status of `Pending virus scan`

## Developer review

- [ ] Code review [PR 116](https://github.com/usdoj/foia-api/pull/116)

### Setup

- [x] Check out `doj-453-dg` branch
- [x] Obtain a fresh database`blt sync`
- [x] Import config `drush cim`
- [x] Set `Test Form` as the `Request Submission Form` for the `Office of Information Policy` `Agency Component`

### Test

- [x] Run all automated tests `blt tests:all`
- [x] See that all automated tests pass
- [ ] Run through functional review steps above

**Comment by malikkotob** [comment]
@dangur placing back in dev to address some feedback in the PR.

**Comment by dangur** [comment]
@malikkotob This is ready for review again.

**Comment by Tom-Camp** [comment]
@dangur - following the _Functional Review_ steps, I submitted the form twice with attachments and the were both __Queued for submission__
