### ISSUE TITLE
Create Cron Job to Batch Scan Files

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#454]
As a security analyst, to ensure that files transmitted from the portal do not contain viruses, I need a file scanning process that provides affirmative confirmation that infected files have been stripped prior to transmission.

Task: Create cron job to batch scan uploaded files, delete virus infected files, and send results of all scans to file entity updater

Implementation notes: set this to run on unix cron, not drupal cron.  We want to be able to control the time more finely than drupal cron

## Acceptance criteria

- [x] Cron job configured to batch scan files for viruses
- [x] Deletes infected files
- [x] Send results of scan to [Entity File Updater](https://github.com/usdoj/foia.gov/issues/455)

## Functional review

- [x] Go to /node/6956/edit
- [x] Ensure that the `Request Submission Form` field is set to `Test Form`
- [x] Go to /form/test-form
- [x] Enter at least one character in the required `Your request` field
- [x] Upload a text file to the `Upload additional documentation` field
- [x] Go to `https://cloud.acquia.com/app/develop/applications/a85801b3-4eb8-447f-bc76-6b5c6a980105/environments/41832-a85801b3-4eb8-447f-bc76-6b5c6a980105/cron`
- [x] Click the `Edit` link in the `Virus Scan` row
- [x] Append ` | mail -s "foia clam results every 5 minutes" your.email@address.com` to the `Command` field (replacing your email address with `your.email@address.com`) to email yourself the scan results
- [x] Wait at most 10 minutes
- [x] Check your email to see the results
- [x] See that the number of scanned files is greater than zero
- [x] See that the number of infected files is zero
- [x] Note the number of scanned files
- [x] Ask Dan, Malik, or Tom to edit one of the text files you uploaded to contain only the string `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`
- [x] Wait at most another 10 minutes
- [x] Check your email again to see the results
- [x] See that the number of infected files is 1
- [x] Ask Dan, Malik, or Tom to verify that the infected file has been deleted
- [x] Wait at most another 10 minutes
- [x] See that the number of infected files is zero

## Developer review

No PR to be merged for this work.

### Tests
- [ ] Complete the functional review steps above

**Comment by Tom-Camp** [comment]
@dangur @malikkotob  - This a CR PASS, but the _Functional Review_ steps need some work.

**Comment by malikkotob** [comment]
This work can be considered complete.
