### ISSUE TITLE
Create file entity updater 

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#455]
As a security analyst, to ensure that files transmitted from the portal do not contain viruses, I need a file scanning process that provides affirmative confirmation that infected files have been stripped prior to transmission.

Task: Create file entity updater to take input from cron job and update the status of file entities

## Acceptance criteria

- [x] On cron run File Entities associated with files that have a Clam AV output status of `Removed.` assume the status of `Virus`
- [x] On cron run File Entities associated with files that have a Clam AV output status of `OK` will assume the status of `Clean`

## Functional review

- [x] Go to /form/test-form
- [x] Enter some characters into the required `Your request` field
- [x] Attach a file that simulates a virus with a `.txt` extension containing only the string `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`
- [x] Attach another file that does not have a virus
- [x] Attach a text file that is empty
- [x] Press the `Submit` button
- [x] Go to /admin/content/files
- [x] Right-click the link of the name of each one of your files to open them in new tabs
- [x] You may see that the statuses of the File Entities are`Scan` if so, wait until 15 seconds after the next minute
- [x] Refresh the tabs with the files from the above steps
- [x] See that the statuses of the file with no virus is `Clean`
- [x] See that the statuses of the file with a simulated virus is `Virus`
- [x] See that the statuses of the empty file is `Clean`

## Developer review

- [x] Code review [PR 122](https://github.com/usdoj/foia-api/pull/122)

### UAT Setup

- [x] Deploy `doj-455-dg-2` to UAT environment
- [x] Import canonical db
- [x] Import config `drush cim`
- [x] Uninstall simplesamlphp_auth contrib module
- [x] Be sure that `Test Form` is selected for `Office of Information Policy` `Request Submission Form`
- [x] Run cron `drush cron`

### UAT Testing

- [x] Complete Functional review steps above
- [x] Go to https://cloud.acquia.com/app/develop/applications/a85801b3-4eb8-447f-bc76-6b5c6a980105/environments/41832-a85801b3-4eb8-447f-bc76-6b5c6a980105/logs
- [x] Select only watchdog logs
- [x] See that the file deletion and status set to virus has been logged
- [x] See that the update completed in under 1 second
- [x] Run all automated tests `blt tests`
- [x] See that all automated tests pass

### Local Setup
- [x] Check out `doj-455-dg-2`
- [x] Get a fresh DB `blt sync`
- [x] Import config `drush cim`
- [x] Uninstall SimpleSAMLphp Auth module `drush pmu simplesamlphp_auth`
- [x] Run cron `drush cron`
- [x] Clear cache `drush cr`
- [x] ssh into local `vagrant ssh`
- [x] Go to the next submission directory `cd /var/www/dojfoia/files-private/webform/test_form/226`
- [x] Delete all existing files `rm *`
- [x] Double escape the delimter on line 51 of foia_file.drush.inc from `\n` to `\\n`

### Local Testing
- [x] Fill in the required `Your request` field at `form/test-form`
- [x] Upload three files at `form/test-form`
  - [x] `a.test.txt` file
  - [x] `a.test.virus.txt` file with only the string `X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*` in it
  - [x] `a.test.empty.file.txt` file
- [x] Submit the form
- [x] Go to `/admin/content/files`
- [x] See that the files have the status of scan
- [x] Simulate the cron command `drush feu "/var/www/dojfoia/files-private/webform/test_form/226/a.test_.txt: OK\n/var/www/dojfoia/files-private/webform/test_form/226/a.test_.empty_.file_.txt: Empty file\n/var/www/dojfoia/files-private/webform/test_form/226/a.test_.virus_.txt: Removed."`
- [x] See the following output from drush:
  - [ ] `The file /var/www/dojfoia/files-private/webform/test_form/226/a.test_.virus_.txt was detected on the filesystem and a virus was detected in it. The file should have been deleted by the scanner.`
- [x] Delete all the files in the `/var/www/dojfoia/files-private/webform/test_form/226/` directory
- [x] Run the above cron simulation command again
- [x] See that the output now is ```The file /var/www/dojfoia/files-private/webform/test_form/226/a.test_.txt was not detected on the filesystem but was marked as clean by the virus scanner.                                                                                                                                                [warning]
The file /var/www/dojfoia/files-private/webform/test_form/226/a.test_.empty_.file_.txt was not detected on the filesystem but was marked as clean by the virus scanner.```
- [x] Simulate a bogus scan output `drush feu "bogus"`
- [x] See the message `An unexpected scan status was detected in the virus scan output.`

**Comment by ba66e77** [comment]
I"m seeing watchdog entries like the ones below on cron.  Moving this back to dev to get those looked at.

```
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||The file test_form/241/a.txt was not detected on the filesystem and was marked as clean by the virus scanner.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||An invalid path of , filename of , or extension of  was detected.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||The file test_form/241/a_0.txt was not detected on the filesystem and was marked as clean by the virus scanner.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||An invalid path of , filename of , or extension of  was detected.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||The file test_form/261/notEicar.txt was not detected on the filesystem and was marked as clean by the virus scanner.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||An invalid path of , filename of , or extension of  was detected.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||The file test_form/271/notEicar.txt was not detected on the filesystem and was marked as clean by the virus scanner.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||An invalid path of , filename of , or extension of  was detected.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||The file test_form/276/notEicar.txt was not detected on the filesystem and was marked as clean by the virus scanner.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||An invalid path of , filename of , or extension of  was detected.
Dec 26 17:30:14 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309414|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||The file test_form/281/notEicar.txt was not detected on the filesystem and was marked as clean by the virus scanner.
Dec 26 17:30:15 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309415|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||An unexpected status was detected in the virus scan output.
Dec 26 17:30:15 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309415|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||An invalid path of , filename of , or extension of  was detected.
Dec 26 17:30:15 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309415|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||A virus was detected in the file /var/www/html/foia.uat/acquia-files/files-private/webform/test_form/286/eicar.txt. The file has been deleted. The associated Entity ID 271 has been set to virus.
Dec 26 17:30:15 staging-27300 foiauat: http://foiauat.prod.acquia-sites.com|1514309415|foia_file|127.0.0.1|http://foiauat.prod.acquia-sites.com/||0||File Entity update completed in 0.14418816566467 seconds.
```

**Comment by ba66e77** [comment]
Merged to `file-scanning` branch.  Closing
