### ISSUE TITLE
Create cron job to check for request entities awaiting scanning.

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#456]
As a security analyst, to ensure that files transmitted from the portal do not contain viruses, I need a file scanning process that provides affirmative confirmation that infected files have been stripped prior to transmission.

Task: Create cron job to check for request entities awaiting scanning, check the status of the associated files, and update request entity status to 'Queued for Submission' if all files are scanned. Also add the request to the queue.

Implementation notes: set this to run on unix cron, not drupal cron.  We want to be able to control the time more finely than drupal cron

## Acceptance criteria

- [ ] On cron run FOIA Requests with associated with files that have been scanned by Clam AV are queued for submission to the relevant Agency Component
- [ ] FOIA Requests with files still to be scanned are not queued.

## Developer review

- [ ] Code review [PR 129](https://github.com/usdoj/foia-api/pull/129)

### Testing

- [x] log in as an administrator user
- [x] run `drush queue-list` to check the number of items queued
- [x] go to the _Content_ page, (`/admin/content`)
- [x] find the _Agency Component_ **Office of Information Polic**
- [x] edit it, setting the **Request Submission Form** to _Test Form_
- [x] go to the _Test Form_ (`/form/test-form`)
- [x] fill out the required field **Your request**
- [x] add a couple of attachments
- [x] go to the _FOIA Request_ page (`/admin/content/foia-requests`)
- [x] note that the new Request _Status_ is set to __Pending virus scan__
- [x] run `drush qcr` to attempt to queue the latest Request
- [x] run `drush queue-list` to check the number of items queued again
- [x] the number should be the same as when you ran it before. The newly create Request should not have been queued.
- [x] run `drush sqlq 'select * from file__field_virus_scan_status where 1;'`, note that the new files are set to __scan__
- [x] update the FileEntity setting the _Virus Scan Status_ to either `clean` or `virus` or setting one to `clean` and another to `virus`. Example `drush sqlq 'update file__field_virus_scan_status set field_virus_scan_status_value = "clean" where entity_id = 181'`
- [x] run `drush qcr` again
- [x] refresh the _FOIA Request_ page
- [x] the _Status_ for the lastest Request has changed to __Queued for submission__

We will need to set up the cron job on UAT in order to properly test this.

**Comment by ba66e77** [comment]
Currently this is blocked by rework needed on 455.

**Comment by Tom-Camp** [comment]
https://github.com/usdoj/foia-api/pull/129

**Comment by ba66e77** [comment]
merged to file-scanning branch
