### ISSUE TITLE
Update submission queue handler

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#457]
As a security analyst, to ensure that files transmitted from the portal do not contain viruses, I need a file scanning process that provides affirmative confirmation that infected files have been stripped prior to transmission.

Task: Update existing request queue worker to only run on requests which have been scanned (consider creating separate queue if we run into bottlenecks)

UPDATE: New task is to update the submission queue handler to no longer queue foia requests with a status of 'scan'.

## Acceptance criteria

- [x] A submission that contains no attachments is queued right away.
- [x] A submission that contains attachments is not queued.

### Functional Review
- [x] Log in to the UAT environment
- [x] Go to the __Content page__ (`/admin/content`)
- [x] Find and edit the __Agency Component__ *Office of Information Policy*
- [x] Under *Request Submission Form* add __Test Form__
- [x] Go to the _Test Form_ (`/form/test-form`) and submit the form without an attachment
- [x] Under *Request Submission Form* add __Test Form__
- [x] Go the **FOIA Request page*** (`/admin/content/foia-requests`)
- [x] Your form submission should be listed with a __status__ of *Queued for submission*
- [x] Go to the _Test Form_ and submit the form with an attachment
- [x] Go the **FOIA Request page*** (`/admin/content/foia-requests`)
- [x] Your form submission should be listed with a __status__ of *Pending virus scan*

### Developer Review
- [x] Review PR https://github.com/usdoj/foia-api/pull/125
- [x] Run `drush queue-list`. Note the number of items in the queue.
- [x] Log in
- [x] Go to the __Content page__ (`/admin/content`)
- [x] Find and edit the __Agency Component__ *Office of Information Policy*
- [x] Under *Request Submission Form* add __Test Form__
- [x] Go to the _Test Form_ and submit the form without an attachment
- [x] Run `drush queue-list` again. It should have incremented by one.
- [x] Go to the _Test Form_ and submit the form with an attachment
- [x] Run `drush queue-list` again. It should not have incremented.

**Comment by Tom-Camp** [comment]
- [ ] Run {{drush queue-list}}. Note the number of items in the queue.
- [ ] Log in
- [ ] Go to the __Content page__ ({{/admin/content}})
- [ ] Find and edit the __Agency Component__ *Office of Information Policy*
- [ ] Under *Request Submission Form* add __Test Form__
- [ ] Go to the _Test Form_ and submit the form without an attachment
- [ ] Run {{drush queue-list}} again. It should have incremented by one.
- [ ] Under *Request Submission Form* add __Test Form__
- [ ] Go to the _Test Form_ and submit the form with an attachment
- [ ] Run {{drush queue-list}} again. It should not have incremented.

**Comment by Tom-Camp** [comment]
### Functional Review
- [ ] Log in
- [ ] Go to the __Content page__ (`/admin/content`)
- [ ] Find and edit the __Agency Component__ *Office of Information Policy*
- [ ] Under *Request Submission Form* add __Test Form__
- [ ] Go to the _Test Form_ (`/form/test-form`) and submit the form without an attachment
- [ ] Under *Request Submission Form* add __Test Form__
- [ ] Go the **FOIA Request page*** (`/admin/content/foia-requests`)
- [ ] Your form submission should be listed with a __status__ of *Queued for submission*
- [ ] Go to the _Test Form_ and submit the form with an attachment
- [ ] Go the **FOIA Request page*** (`/admin/content/foia-requests`)
- [ ] Your form submission should be listed with a __status__ of *Pending virus scan*

**Comment by malikkotob** [comment]
@Tom-Camp this looks good for the most part. Left some minor comments in the PR!

**Comment by malikkotob** [comment]
@Tom-Camp super close. A couple more minor things to address in the PR.

**Comment by malikkotob** [comment]
Merged into the `file-scanning` integration branch.
