### ISSUE TITLE
Update email and API sending routines

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#458]
As a security analyst, to ensure that files transmitted from the portal do not contain viruses, I need a file scanning process that provides affirmative confirmation that infected files have been stripped prior to transmission.

Task: Update email and API sending routines to list the names of files marked as removed rather than trying to attach/encode them.

Implementation notes: this may require adding an element to the JSON schema sent via API

## Acceptance criteria

- [x] Emails sent to components list the names of files containing viruses that were deleted
- [ ] API requests sent to components list the names of files containing viruses that were deleted

## Developer review

These steps will need to be done on a server that sends emails.

- [x] log in as an administrator user
- [x] go to the Content page, (`/admin/content`)
- [x] find the _Agency Component Office of Information Policy_
- [x] edit it, setting the __Request Submission Form__ to _Test Form_
- [x] change the __Submission Email__ to your email address
- [x] go to the __Test Form__ (`/form/test-form`)
- [x] fill out the required field __Your request__
- [x] add a couple of attachments
- [x] in order to test properly we will need to attach the test virus file
- [x] go to the _FOIA Request_ page (`/admin/content/foia-requests`)
- [x] note that the new _Request Status_ is set to __Pending virus scan__
- [x] the cron job for the file scanning runs every minute, so you may need to wait a moment before proceeding
- [x] run `drush qcr` to queue your latest Request
- [x] go to the _FOIA Request_ page (`/admin/content/foia-requests`)
- [x] note that the new Request Status is set to _Queued for submission_
- [x] run `drush queue-run foia_submissions`
- [x] you should recieve an email containing the details of the submission.
- [x] the files should be listed. If there was a virus file, it should be noted that _ A virus was detected in this file and it was deleted._

* We will need to update the API definitions to include the field __removed_files__.
* Currently we don't have a good way to test the API submissions.

**Comment by Tom-Camp** [comment]
PR: https://github.com/usdoj/foia-api/pull/130

**Comment by dangur** [comment]
![new_foia_request_received_for_office_of_information_policy_-_dan_gurin_civicactions_com_-_civicactions_mail](https://user-images.githubusercontent.com/307044/34393444-5d3d3cd4-eb20-11e7-976b-8abe48331e85.png)

**Comment by dangur** [comment]
There is a warning that we get when the queue is run because the file has been deleted:
```
$drush queue-run foia_submissions
file_get_contents(a.test_.virus_.txt):  [warning]
failed to open stream: No such file or directory EmailWebformHandler.php:812
```

**Comment by ba66e77** [comment]
Merged to `file-scanning`.  The warning @dangur noted above he filed as #483 for tracking purposes and follow-up.
