### ISSUE TITLE
No instructions for completing PROCESSING DATA fields 

### ISSUE THREAD

**Issue by cnovick-doj** [usdoj/foia.gov#468]
As an Administrator, in order to create or edit and Agency Component, I need detailed instructions describing the data necessary to complete the PROCESSING DATA fields.

Navigate to https://dev-admin.foia.gov/node/add/agency_component or attempt to edit an existing Agency Component

What is the criteria for entering data in these fields?

![processing data capture](https://user-images.githubusercontent.com/29544035/33952510-06274fa0-e000-11e7-9333-034837ef48c6.PNG)

**Comment by brockfanning** [comment]
These fields are automatically populated, and also may be phased out soon. This can be closed for now.
