### ISSUE TITLE
Write contact updater form content/questions for back stage

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#48]
#37 is dependent on this
- [x] start with data in yml already
- [x] use any form interactions already built/tested by 18F/USDS
- [x] include fields so that agencies can provide links to their FOIA regs and their reading room
- [x] sync with drupal dev to check on complication of proposed form
- [ ] build in google form for testing

**Comment by adborden** [comment]
Example agency contact https://github.com/18F/2015-foia/tree/master/contacts/data
and https://github.com/18F/foia-recommendations/tree/master/examples

**Comment by leahbannon** [comment]
Issue #41 also has the contact updater fields.

**Comment by RyanSibley** [comment]
Questions started here: https://docs.google.com/a/gsa.gov/document/d/1ajOavzxdNv6q2vLdANuJ_qFhtXm-QODYcU--1a5w2LI/edit?usp=sharing

**Comment by RyanSibley** [comment]
work started here: https://docs.google.com/a/gsa.gov/spreadsheets/d/1wmzvMFwensrp82gesFqSwP74Q4FwzYnFw0fDewVZ-dg/edit?usp=sharing

**Comment by RyanSibley** [comment]
I'd like to talk to a few members of the team about this before we call this done. I know there are plans to build a google form to test content, but I think we should work through some of the more ambiguous fields as a team to make sure we understand what they mean first. For instance `Service Centers - array of Person` is still unclear in my mind and I'm not sure the question I wrote to gather that info is right.

**Comment by adborden** [comment]
Looks great.

@malikkotob can best explain the array of Person thing. Issue https://github.com/18F/foia/issues/83 has some screenshots which kind of illustrate how Drupal handles this. Each Person is an entity that has a name and a phone number. You can assign any Person to the list of Server Centers people as well as FOIA Officer people.

**Comment by malikkotob** [comment]
I'd like to be able to comment on the work being done here, but think it might be helpful to just get a high-level explanation on the intent of the issue.

In terms of the Service Centers field, @adborden described it accurately. The Person (we called it FOIA Personnel in Drupal) can also be assigned to the public liaisons field as well.
