### ISSUE TITLE
collect site analytics for foia.gov

### ISSUE THREAD

**Issue by RyanSibley** [usdoj/foia.gov#49]
to help determine the usefulness of each page on foia.gov, we should capture site analytics for all the urls. 

The URLs are captured here: https://docs.google.com/spreadsheets/d/12LdK_BjmzGuvTVzcNxicui_Zzo8BOLkN-2dAf9XBWGo/edit?pli=1#gid=0

This issue can be closed when the `analytics` column in the spreadsheet is complete.

**Comment by adborden** [comment]
I think this data is available in DAP, but I'm not sure where to get it all.
