### ISSUE TITLE
Agency Component Handle No Agency

### ISSUE THREAD

**Issue by dangur** [usdoj/foia.gov#492]
Modify front stage to gracefully handle Agency Components that have no Agency associated with them.

## Expected Behavior
- [ ] Typeahead works when an Agency Component does not have an Agency associated with it.

## Actual Behavior
- [ ] Typeahead does not work when an Agency Component does not have an Agency associated with it.

### If issue #491 has not been completed
1. Create an Agency Component that does not have an Agency associated with it.

### If issue #491 has already been completed
1. Create a test Agency
1. Create a test Agency Component
1. Associate the test Agency with the test Agency Component
1. Delete the test Agency

**Comment by brockfanning** [comment]
Just a note that I tried and failed to fix this here: https://github.com/usdoj/foia.gov/pull/494
