### ISSUE TITLE
New Icon for Mailing Address on Contact Information

### ISSUE THREAD

**Issue by mngardner** [usdoj/foia.gov#493]
Please add in an icon for mailing address for contact information.  This will ensure that individuals, phone numbers, emails, and now mailing addresses will have an icon.

**Comment by brockfanning** [comment]
@mngardner Can you point me to an example of a page where you'd like the icon to appear?

**Comment by mngardner** [comment]
@brockfanning - it is right by the mailing address in the contact information on the development site.  Unfortunately, the dev site is going through load testing right now, so i cant take a screen shot.

**Comment by brockfanning** [comment]
@mngardner Seems to be a caching issue with api.data.gov going on with dev, but staging now has the latest code.

**Comment by brockfanning** [comment]
@adborden @leahbannon @hbillings We could use another Picon image for this issue: a mailbox image. Do you think it's possible to use another Picon image? And if so, how would we go about that?

**Comment by adborden** [comment]
I think we should hold-off on the icon until we've got all the contact information into the system.

The original design had three icons for a single contact, but now it seems we'll have at least three contacts appear in that space which means a lot of repeating icons. I don't think adding another one will help.

Once we can see all the contact information, we can make a better call about the icons.

**Comment by brockfanning** [comment]
This was fixed by #555
