### ISSUE TITLE
investigate 10% agency questions

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#51]
Will groom in tactical time today.

**Comment by RyanSibley** [comment]
Summary of takeaway from today's tactical time with OIP: 

Sometimes agencies require fields outside of the already identified or regularly required  fields, or the "90 percent", for legal reasons, such as certifying under law that a person is who they say they are as in the case for the DOJ 360 form. And sometimes it's for ease of search, as in the case for SSNs and the SSA or case numbers for varying agencies.  In many cases, the additional info serves as an "identifiable indicator" for records. 
Examples of additional required fields:

- certification of ID
- Case numbers
- DOB
-`attach supporting docs` option or field
- DOJ 306 form
- alien number (CBP)
-

Some resources: 

-https://www.gpo.gov/fdsys/pkg/FR-2015-04-03/pdf/2015-07772.pdf
- https://www.fbi.gov/services/records-management/foipa/requesting-fbi-records
- Cheif FOIA reports (need link)

Questions that came up for me to be answered in interviews or through further research: 
-Do agencies want or need a separate field for these requirements, or can/should the information be kept within the description of requested records?
- Do we need add a disclaimer or educational materials regarding submitting PII?
-Can we find agencies that require generic case numbers be included (benign numbers that have no PII associated) to see how they'd like these numbers treated and if there are "rules" for their treatment?
-How do the agencies with requirements that easy to ID treat those additional requirements (SSN, DOJ 360, Alien number)

**Comment by adborden** [comment]
Just looking through some of the request forms on FOIA Online, some of the additional fields are not requirements but optional fields. I just want to clarify that these are included in 10%, right?

**Comment by RyanSibley** [comment]
@adborden I was originally considering fields that are required for submitting a FOIA request, but I think an argument can be made for including "nice-to-haves" as well. 

Also, adding an example of a policy requiring identity authentication when making first party requests:

> § 10.37 Identification of individual making request.
No record or information contained in a system of records is disclosed to an individual nor is any correction of a record in accordance with subpart E made at the request of an individual unless that individual demonstrates that he or she is who he or she claims to be. Normally, identity can be proven for individuals who appear in person by the presentation of an identifying document issued by a recognized organization (e.g., a driver's license or a credit card) and which contains a means of verification such as a photograph or a signature. For requests by mail, the unique identifier used in the system should be included if known. Responses to mail requests are normally sent only to the name and address listed in the system of records. In the case of particularly sensitive records, additional identification requirements may be imposed. In such cases, these additional requirements are listed in the public notice for the system.

more info can be found here: https://www.law.cornell.edu/cfr/text/49/10.37

and here: https://www.ecfr.gov/cgi-bin/text-idx?tpl=/ecfrbrowse/Title49/49cfr7_main_02.tpl

**Comment by RyanSibley** [comment]
Privacy requirements from [EPA](https://www.epa.gov/foia/foia-request-process):

> In order to protect your privacy, when you make a written request for information about yourself, you must provide either a notarized statement or a statement signed under penalty of perjury stating that you are the person you claim to be. You may fulfill this requirement by:
having your signature on your request letter witnessed by a notary, or
pursuant to 29 U.S.C. 1746 (2) including the following statement just before the signature on your request letter: "I declare under penalty of perjury that the foregoing is true and correct. Executed on [date]." If you request information about yourself and do not provide one of these statements, your request cannot be processed under the Privacy Act. This requirement helps to ensure that private information about you will not be disclosed to anyone else.

**Comment by RyanSibley** [comment]
DOI FOIA regs: https://www.ecfr.gov/cgi-bin/text-idx?c=ecfr&sid=0fc3ab3499768eebc2e3691c8cf88dec&rgn=div5&view=text&node=43:1.1.1.1.2&idno=43

**Comment by RyanSibley** [comment]
Doc with examples of privacy act language: https://docs.google.com/a/gsa.gov/document/d/1gpTa1dE5BeQjn5p5CJwhpP60Q013qjteskUzH6qgzuM/edit?usp=sharing

**Comment by adborden** [comment]
If we don't include the optional fields in the 10%, where would we include them? I think Matt said that required fields only make up a tiny bit of the 10%. I was under the impression that this is important to agencies because they can't put every helpful piece of info into their regs, hence optional.

**Comment by RyanSibley** [comment]
We haven't yet decided if we can get an exhaustive list of this types of info without asking for it from every agency and agency component. However, we have identified what the team agrees is good sample of the types of info that could be requested that isn't common to all requests. One more step in this research should be to identify a "vital few" agencies based on FOIA reports and look at their requirements. The current 10 percent info is in this spreadsheet:

https://docs.google.com/a/gsa.gov/spreadsheets/d/1eJ1Bzug6Q_jtXdHtzpStIcEHva9-QWCbvhw0GjOrAw8/edit?usp=sharing

**Comment by RyanSibley** [comment]
@vz3 can you review this and make note of next steps in a new issue?
