### ISSUE TITLE
Add USWDS to foia

### ISSUE THREAD

**Issue by adborden** [usdoj/foia.gov#53]
Pull in the [US Web Design Standards](https://www.npmjs.com/package/uswds) source from npm so that we can extend and control the styles with specific granularity.

**Acceptance criteria**
- [x] uswds is pulled in from npm so that we can keep up to date with new versions
- [x] Apply the uswds grid to the jekyll layout templates (no need to apply grid to existing foia.gov content)

**Comment by hbillings** [comment]
So after tooling around with this for a while, I think the second criterion is something worth discussing. The way the standards are currently organized makes this pretty fragile and time-consuming to get right. (The USWDS team told me that while pulling out individual components is part of "an ideal future," it isn't currently supported.)

For example, while trying to get the grid working, I realized that not only do I have to import `/node_modules/uswds/src/stylesheets/core/_grid.scss`, I also have to import the dozen or so files in `/node_modules/uswds/src/stylesheets/lib/grid` or else the Bourbon/Neat mixins aren't defined. WDS currently imports Bourbon/Neat deps in its complete file at `uswds.scss`.

I feel like the modularity we're going for here is going to end up making things more complex than they need to be and susceptible to breaking when modifications need to be made or pieces need to be added. :-/

**Comment by adborden** [comment]
Sounds good to me. I just removed that AC.
