### ISSUE TITLE
Exit popup for non-government external links

### ISSUE THREAD

**Issue by brockfanning** [usdoj/foia.gov#538]
As a site user, in order to be warned before viewing a non-government site, I need to see a popup whenever I click on an external non-government link.

## Expected Behavior

When clicking on external non-government links, a popup should appear before the user goes to the target.

## Actual Behavior

Currently external non-government links go directly to the target.

## Steps to reproduce the behavior

1. Visit the homepage
1. Click on the "Hero image credit" link in the footer.

**Comment by brockfanning** [comment]
@mngardner @btalebian @gsolomon123
Here is a screenshot of what I've got working. This is a popup that would appear whenever a user clicks on an external link that doesn't end in .gov or .mil. After 5 seconds, the user is automatically carried on to the destination they clicked on. (that number of seconds is configurable, as is any of the language).

FYI, this is modeled after what DOJNet does. To see that, go [here](https://dojnet.doj.gov/) and click on the "AG News Briefing" sidebar image.

![foia-exitscript](https://user-images.githubusercontent.com/1319083/36213985-2a52c5d8-1176-11e8-893d-4e5cb848d014.png)

**Comment by mngardner** [comment]
@brockfanning @btalebian - this looks good to me.  Lets go ahead with it.  Thanks.

**Comment by gsolomon123** [comment]
@brockfanning @btalebian @mngardner Would it be better if it could say "You are now leaving FOIA.gov?"  If we leave it as is, "web site" should be one word.  Thank you.

**Comment by brockfanning** [comment]
@gsolomon123 @btalebian @mngardner I've updated it to say "You are now leaving FOIA.gov" and merged it into dev-www.foia.gov. It will be included in the next front-stage release, which we can do at any point.
