### ISSUE TITLE
Email Theming Changes

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#541]
As an agency user, in order to easily read FOIA requests received via email, I need the request formatted vertically (in addition to the current horizontal format).

## Acceptance criteria

- [ ] Data is displayed in both vertical and horizontal formats
- [ ] There is a note or heading explaining that two formats are available

**Comment by brockfanning** [comment]
@kristusacquia @mngardner @btalebian Here's a screenshot of a test email sent from the dev server. Any feedback?

![foia-email-format](https://user-images.githubusercontent.com/1319083/36165829-c235b080-10be-11e8-9520-8608aadaf820.png)

**Comment by mngardner** [comment]
@brockfanning - that looks good to me - the only comment I would have is can you bold the field names on the vertical layout just like they are on the horizontal layout?

**Comment by brockfanning** [comment]
@mngardner Sure, here's that change:

![foia-email-format-bold](https://user-images.githubusercontent.com/1319083/36172751-e1bc02ea-10d4-11e8-8175-f6313cd4b694.png)

**Comment by mngardner** [comment]
@brockfanning - thanks it looks good.  Lets push those changes whenever you are ready.

**Comment by brockfanning** [comment]
@mngardner This went up with the last back-stage release, so I'm closing it out.
