### ISSUE TITLE
Investigate and develop password management solution

### ISSUE THREAD

**Issue by kristusacquia** [usdoj/foia.gov#542]
Task: Investigate and estimate a solution that meets the requirements expressed in the following story.

As a system administrator, in order to ensure that Drupal accounts & passwords for Agency Managers are renewed quarterly, I need a solution that will automatically initiate the renewal process (according to a predefined schedule or interval) and force a password reset.

## Acceptance criteria

- [x] Confirm a solution that meets the requirements
- [x]  Prepare an estimate for the solution
- [x] Develop solution

## Functional Review

**Create agency manager**
- [ ] Visit https://dev-admin.foia.gov
- [ ] Login as an agency administrator (not an admin and not an agency manager) (if you do not have access as a user with this role, contact Malik for test user info)
- [ ] Go to https://dev-admin.foia.gov/admin/people/create
- [ ] Check the 'Non-SSO' role
- [ ] Enter an email address, username, and ANY password 
- [ ] Uncheck the "Enable this user to leverage SAML authentication" checkbox
- [ ] Set the agency to "Department of Justice" 
- [ ] Click "Create new account"
- [ ] A message should appear at the top of the screen "Created a new user account for <username>."
- [ ] Click the username in the message
- [ ] Click the edit tab when the user's profile loads
- [ ] Enter a temporary password for the user that complies with the password policy (note the username and password somewhere, as you will need them in subsequent steps)
- [ ] Check the "Password Expiration" checkbox to force the new user to change their password upon login
- [ ] Save the changes
- [ ] Logout of the agency administrator account

**Login as agency manager and verify password reset process**
- [ ] Visit /user/login
- [ ] Using the username and password you set above, login as the agency manager
- [ ] Verify there is a message at the top of the screen indicating you are required to change your password
- [ ] Click the "View" tab at the top of the page
- [ ] Verify you are unable to leave the current page and the password change message persists
- [ ] Enter the current password, and fill out a new password that complies with the password policy in the two password fields (Take note of the new password)
- [ ] Save
- [ ] Verify you are now able to click the "View" tab
- [ ] Logout of the account and log back in with the same username and new password
- [ ] Verify you are able to login with no issues

**Simulate 90 day period of time**
- [ ] Log back in to the agency administrator account
- [ ] Go to /admin/people
- [ ] Click edit by the agency manager user you created
- [ ] Verify the "password expiration" checkbox is unchecked
- [ ] In the "Last Password Reset" field enter a date more than 90 days in the past
- [ ] Enter a new password for the user that complies with the password policy (take note of this password)
- [ ] Click "Save"
- [ ] Wait a couple of minutes
- [ ] Refresh the page
- [ ] Verify the "password expiration" checkbox is now checked (this indicates that the user's password has expired)
- [ ] Logout of the agency administrator account

**Repeat agency manager reset steps**
- [ ] Repeat steps under section titled "Login as agency manager and verify password reset process"

**Comment by malikkotob** [comment]
Merged and released on 02/20/18.
