### ISSUE TITLE
OIP: FOIA.gov back button enhancement

### ISSUE THREAD

**Issue by vivbutler** [usdoj/foia.gov#574]
As a anonymous user of FOIA.gov, So that I can email links to pre-selected agencies and so that the Back button will work correctly, I need to be able to go directly to the homepage with an agency already pre-selected

[Description, background context, or implementation details]

## Acceptance criteria

Scenario: Back button works
Given I am on the homepage
And I click “Start your request”
And I type in “treasury”
And I select “Department of the Treasury”
And I click “FOIA Reference Guide”
And I click the Back button
Then I should still see the details for the Department of the Treasury

Scenario: Emailed links work
Given that I visit https://www.foia.gov?agency=department-of-the-treasury
Then the page should automatically scroll down to the pre-selected details for the Department of the Treasury

## Steps to reproduce the behavior

1.
1.
1.

**Comment by lamontwalton** [comment]
@jhuang0427 something technical

**Comment by brockfanning** [comment]
This was completed in #729
