### ISSUE TITLE
Mobile navigation bugs

### ISSUE THREAD

**Issue by maya** [usdoj/foia.gov#576]
There are various bugs in the mobile navigation:

- sits too low 
- uses different font sizes
- uses inconsistent icons when expanded
- colored states when expanded

When styling the USWDS navigation, it's best to add desktop sizes in desktop-specific media query. Since it's built mobile-first the mobile sizes would not be altered.

## Expected Behavior
<img width="432" alt="screen shot 2018-03-09 at 12 39 27 pm" src="https://user-images.githubusercontent.com/5249443/37228836-d29a3e2e-2396-11e8-8418-ce7903e1c381.png">

## Actual Behavior

<img width="320" alt="screen shot 2018-03-09 at 11 43 40 am" src="https://user-images.githubusercontent.com/5249443/37228774-9e0a154e-2396-11e8-9a1a-470e70106cc0.png">
<img width="396" alt="screen shot 2018-03-09 at 11 46 48 am" src="https://user-images.githubusercontent.com/5249443/37228870-efec9ab2-2396-11e8-8758-54566416a52e.png">

**Comment by brockfanning** [comment]
@maya Thanks for pointing these out, great points!

**Comment by brockfanning** [comment]
@maya Thanks again. These should be fixed now. (a mere 15 months later!)
