### ISSUE TITLE
Provide list of all agencies on homepage

### ISSUE THREAD

**Issue by brockfanning** [usdoj/foia.gov#609]
As a requester with no knowledge of government agencies, I need to be able to get to a list of all agencies while on the homepage, to help me figure out which agencies might be applicable to my request.

**Comment by brockfanning** [comment]
@mngardner @btalebian Thinking about how to implement this, it seems like it might be more useful if the list were grouped by topic, like [the usa.gov page](https://www.usa.gov/contact-by-topic). We would need to implement a new taxonomy field, but how do you feel about something like this:
![agency-components-by-topic-1](https://user-images.githubusercontent.com/1319083/38823458-6309e068-4174-11e8-800d-8df68109ed48.png)
![agency-components-by-topic-2](https://user-images.githubusercontent.com/1319083/38823456-62d4970a-4174-11e8-9c1b-87413584acc1.png)
![agency-components-by-topic-3](https://user-images.githubusercontent.com/1319083/38823457-62f331a6-4174-11e8-925a-5fc71ffc3f47.png)

**Comment by mngardner** [comment]
@brockfanning - wow that is really cool.  I like that very much - perhaps if we replicate that functionality, we wont have to link away from the site - we could reformulate that section on USA.gov to point inward to this new feature.  Thanks!  I like this direction.

**Comment by brockfanning** [comment]
@mngardner Ok great - question: should this list be of the 116 agencies (/admin/structure/taxonomy/manage/agency/overview in the backstage) or the 439 agency components (/admin/content?title=&type=agency_component in the backstage)?

**Comment by mngardner** [comment]
@brockfanning - it should be the 116 list.

**Comment by brockfanning** [comment]
@mngardner Ok, so then if you agree, I will start things off with a backstage change adding a new taxonomy field called "Topic" to the agency vocabulary. Then, once we've assigned a Topic to each of the 116 agencies, we can move forward with this frontstage feature. Does that sound good?

**Comment by mngardner** [comment]
@brockfanning - that sounds great.

**Comment by brockfanning** [comment]
@mngardner @btalebian This addition to the homepage is available for testing on the dev-www site. Note that I only categorized a few random agencies, just to give you the basic idea.

**Comment by brockfanning** [comment]
This was completed with #730. We still have the option of a topic-based selection tool.
