### ISSUE TITLE
Review and classify existing foia.gov UI components

### ISSUE THREAD

**Issue by adborden** [usdoj/foia.gov#61]
In order to implement a new visual design in small increments, without taking on the whole thing, we need an idea of what existing UI components are re-usable and what issues might exist with them.

**Acceptance criteria**
- [x] timebox to a few hours
- [x] start with form elements on the site
- [x] create a list of components on foia.gov
- [x] assess how reusable the component is, and any CSS classes relevant to it's use
- [x] note any issues or challenges you see in using them
- [x] identify if they use a CSS framework
- [x] identify if they use a grid

**Comment by hbillings** [comment]
My efforts at this can be found here (private link): https://docs.google.com/document/d/19p7fbwifjl64ZxvuZIrZtS7GAe6XyGjYHaubwfgwPIc/edit#

The upshot is that none of this seems very reusable. It mostly is not even reusing its own styles, leaning heavily on IDs.
