### ISSUE TITLE
Downloadable agency component contact information

### ISSUE THREAD

**Issue by brockfanning** [usdoj/foia.gov#610]
As a non-technical user, in order to get up-to-date information in bulk about all agencies, I need to be able to download a CSV of the latest agency component contact information.

**Comment by brockfanning** [comment]
Data columns needed are as follows:

- Component
- Department
- Name
- Title
- Room Number
- Street Address
- City
- State
- Zip Code
- Telephone
- Fax
- Website

**Comment by brockfanning** [comment]
@mngardner Just wanted to clarify, should this spreadsheet have one row per agency component, or one row per FOIA personnel?

**Comment by brockfanning** [comment]
@mngardner I could also use some clarifications about the sources of the data, in the back stage. Can you confirm what I have below is correct and also respond to any questions?

1. Component: the "Agency Component Name" of the agency component
2. Department: the "Name" of the Agency associated with the agency component
3. Name: the "Name" of the FOIA personnel associated with the agency component -- **Question: Should we be looking only at "FOIA Officers", or also including the personnel in "Public Liasons", "Service Centers", and/or "Misc"?**
4. Title: the "Title" of the FOIA personnel associated with the agency component
5. Room Number: Question: **I don't believe this is available in the back stage -- am I missing it?**
6. Street Address: from the "Submission Address" of the agency component
7. City: from the "Submission Address" of the agency component
8. State: from the "Submission Address" of the agency component
9. Zip Code: from the "Submission Address" of the agency component
10. Telephone: **Question: Should this be from the "Submission Address" of the agency component, or should it be from the "Phone number" of the FOIA personnel?**
11. Fax: the "Fax Submissions" of the agency component
12. Website: the "Website" of the agency component

Also I didn't see Email in the example spreadsheet - should Email be included in this data? If so, should it be the email address associated with the agency component or with the FOIA personnel?

**Comment by mngardner** [comment]
@brockfanning - i guess we would need to provide all of the individuals so probably each row would be an individual and we could merge the cells together to represent the whole agency or component where appropriate.  As to the email - lets include email if its in the system, but not the submission email that used to actually send the request -- only an email if it is associated with a individual position.

**Comment by brockfanning** [comment]
@mngardner Thanks, understood about the rows and emails. Do you have any thoughts on the questions in 3 and 5 above? (For my question in 10, I'm going to assume it should be the FOIA personnel phone number, since that's the approach you want for emails.)

**Comment by mngardner** [comment]
for 3:  We should include Officer, Liaison, and Service Center - Not Misc.
for 5:  Any room number listed would be included in the actual mailing address itself - its not a separate field.
for 10:  Yes the phone number should be associated with that personnel.

**Comment by brockfanning** [comment]
@mngardner Thanks again. Regarding 3 - if including Officer, Liaison, and Service Center - is it OK for a personnel name to be repeated on multiple rows? See NSA as an example.

**Comment by mngardner** [comment]
Yes - that is fine @brockfanning

**Comment by brockfanning** [comment]
@mngardner Great! Hopefully last question - would it be acceptable if this functionality were only available on the back stage? I'm assuming the answer is no, but I have to ask because it would drastically change the way it was implemented.

**Comment by mngardner** [comment]
@brockfanning - i think having it on the front stage for requesters to pull would be the most helpful.  If there are some limitations with that, we could come up with a mechanism by which the backstage report is run monthly or something and then posted on the frontstage - although i think in the long run it would be better to just have the data be available on the front stage directly.

**Comment by brockfanning** [comment]
@mngardner @btalebian This has been merged and is up on the dev site. The final step is to decide where this new page will be linked from. (navigation item? or link on an existing page?)

Here is the new page: https://github.com/usdoj/foia.gov/blob/develop/www.foia.gov/full-foia-contacts.md

**Comment by mngardner** [comment]
@brockfanning - I think it would be great to have the download on the "developer resources" page.  This is where it was on the archive site, and requesters and agencies already have familiarity with it being there.  Thanks!!

**Comment by brockfanning** [comment]
@mngardner No problem, it's now at the bottom of that page on the dev site.

**Comment by mngardner** [comment]
@brockfanning  - that looks great.  Amazing Job!
