### ISSUE TITLE
BOD-18-01 compliance for admin.foia.gov, dev-admin.foia.gov, and stg-admin.foia.gov

### ISSUE THREAD

**Issue by jhuang0427** [usdoj/foia.gov#657]
Please make backstage code changes so that the sites below are in compliance with BOD-18-01.

I’m attaching a spreadsheet which shows the reported issues for each site.   The domains are dinged for not using strong hsts.

admin.foia.gov
dev-admin.foia.gov
stg-admin.foia.gov

**Comment by brockfanning** [comment]
This was resolved, closing.
