### ISSUE TITLE
Create accordions on FOIA.gov home page

### ISSUE THREAD

**Issue by gsolomon123** [usdoj/foia.gov#661]
As a web author, in order to reduce some of the text on the FOIA.gov home page, I need accordions created.

Please apply the USWDS accordions component to the text on the FOIA.gov home page that’s in this block:

“Do research and determine if you need to make a FOIA request, then get ready.”

The three columns under that text will each be accordions.

## Acceptance criteria

- [ ]
- [ ]
- [ ]

[Description of defect]

## Steps to reproduce the behavior

1.
1.
1.

**Comment by brockfanning** [comment]
@mngardner @gsolomon123 This is up on the dev site for testing. It turned out that images do work in accordions, so I've left it in 3 columns for now.
