### ISSUE TITLE
Attach formatted PDF on email submissions

### ISSUE THREAD

**Issue by brockfanning** [usdoj/foia.gov#668]
As an agency manager, in order to print nicely formatted versions of submissions, I need an attached PDF version of the submissions.

**Comment by cnovick-doj** [comment]
Which piece of content am I attaching to the email - the FOIA Request entity or the Webform submission entity?

**Comment by brockfanning** [comment]
@cnovick-doj Some of both. It should include the same data that is already being emailed - just as an attached PDF.

**Comment by cnovick-doj** [comment]
@brockfanning @gsolomon123 Code is on stage and ready for testing.

**Comment by cnovick-doj** [comment]
@brockfanning @gsolomon123 Code has been pushed to prod
