### ISSUE TITLE
Add uswds disclaimer header

### ISSUE THREAD

**Issue by adborden** [usdoj/foia.gov#70]
As a requester, in order to trust that this is a government website, I need the familiar WDS disclaimer that I see on many government websites.

As described https://standards.usa.gov/components/headers/#basic, this is just the thin disclaimer that says this is a US government website, not a full header.

## Acceptance criteria

- [x] any pages using the jekyll layout should display the header

**Comment by hbillings** [comment]
Blocked on this until I can figure out how to copy images from `node_modules/uswds` to a place the built site can find them, and where to instantiate the WDS javascript.

**Comment by adborden** [comment]
Spoke to @hbillings on this, we added a build step to copy the assets, and the js import should happen within our entrypoint `requests.jsx` for now.
