### ISSUE TITLE
Migrate phone and abbreviation fields for agency components

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#78]
As an agency component, in order to preserve important data from the 2015 yml data exports, I need phone number and abbreviation to be imported into the system.

As part of working #23, it was noticed that phone and abbreviation were not identified from the data modeling work completed in #16 as fields to be included on the agency component content type in Drupal. Matt confirmed that this data should be imported, and as such, adjustments need to be made to the component content type, as well as the migration script to support this.

## Acceptance criteria

- [x] The `agency_component` content type has `phone` and `abbreviation` fields
- [x] Running the `agency_component` migration script pulls in `phone` and `abbreviation` content from the 2015 source data
- [ ] `schema.md` updated to indicate that these fields will be included in the metadata

**Comment by malikkotob** [comment]
@adborden realized that I closed this before confirming that `schema.md` was updated with these fields. Is this something you were planning on doing, or did you want me to go ahead and submit a PR? If so, where would you want these added exactly? Under the Schema section - https://github.com/18F/foia-recommendations/blob/master/schemas.md#schema?

**Comment by adborden** [comment]
Yes, please go ahead and submit the PR. The Schema section sounds right to me.
