### ISSUE TITLE
Modify maximum character length for name field on FOIA personnel entities

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#79]
As an agency component, in order to preserve the 2015 yml data, I need the full names used for FOIA officers, public liaisons, and service centers to be imported.

In Drupal, FOIA officers, public liaisons, and service centers were modeled using a 'FOIA Personnel' entity. This allows an agency component to add information for 'Joe Worker' one time and reuse that information across the officer, liaison, and service center fields (if Joe happens to handle all three roles for his component). The `foia_personnel` entity was created with a maximum character limit on the name field of 50 characters. This ended up being an issue for components who indicated many names in a comma separated fashion for a single officer or liaison. See [ED.yaml](https://github.com/18F/2015-foia/blob/master/contacts/data/ED.yaml#L20) for an example.

## Acceptance criteria

- [x] FOIA personnel entities can handle a name that is 255 characters long
- [x] FOIA personnel entities are successfully created for the length names found in [ED.yaml](https://github.com/18F/2015-foia/blob/master/contacts/data/ED.yaml#L20) and [SEC.yaml](https://github.com/18F/2015-foia/blob/master/contacts/data/SEC.yaml#L22) after running the `foia_personnel` migration script

**Comment by Tom-Camp** [comment]
I think that we will increase this field to 255 characters.
