### ISSUE TITLE
Handle officers, liaisons, and service centers with no name information from 2015 data

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#81]
As an agency component, in order to handle FOIA personnel with no name defined in the 2015 data, I need default generic names to be used to describe these contacts.

There are cases where FOIA officer, public liaison, and service center data have phone numbers and no names listed. When they're migrated into Drupal they are added as FOIA Personnel entities with a phone number and no name. This scenario should be handled to have a default name tied to these numbers. E.g. if it's a service center number with no name, use 'Service Center Contact', if it's an officer number with no name use 'Officer Contact'.

## Acceptance criteria

- [ ] FOIA personnel with no name info in the 2015 data are given reasonable default names?

**Comment by adborden** [comment]
Icebox for now.

**Comment by adborden** [comment]
I don't think this is an issue, we just display the information we have, and in some cases give them a title based on their role. e.g. The service center phone number might show up as
```
FOIA Service Center
555-5555
````
