### ISSUE TITLE
Write script to import Google Form survey results

### ISSUE THREAD

**Issue by malikkotob** [usdoj/foia.gov#82]
As an agency component, in order to have our component's survey results reflected in the request form on the new portal, I need the survey results imported into Drupal.

## Dependencies

- [ ] The scope and final format of the collected data is defined

## Acceptance criteria

- [ ] Survey results are imported into Drupal, such that each agency's request form reflects the results of the survey

**Comment by adborden** [comment]
#66 is the related dependency. You can check the Google Sheet attached to the form to get an idea of how the fields are evolving.

**Comment by adborden** [comment]
We opted to go for a manual approach. OIP will be manually entering the survey responses for all 400+ agency components.
