### ISSUE TITLE
Round 2 of agency form builder -- write email and instructions

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#87]
As FOIA personnel within an agency, in order to communicate our perfected FOIA request needs, I need a way to validate fields and request new fields to populate the FOIA portal relevant to my agency.

This issue is to write an email and necessary instructions to start scaling the agency form builder to the next round of 10 agencies.

## Acceptance criteria

- [ ] Convey that we need a response by next week if possible
- [ ] We'd like to observe if they are available next week
- [ ] Tell them we can send them xls if they can’t access the google form
- [ ] Figure out instructions for agencies with sub-components - talk to Matt & Victor

**Comment by RyanSibley** [comment]
Some notes about iterating on the survey and where I'm tooling with language for the email:
https://docs.google.com/document/d/1efsoJjPm5BN7mmuCTlcwDAL1HoydSVVIVB1FXAXBPp8/edit

> Please complete this survey to tell us what information is required when people submit FOIA requests according to your agency’s FOIA regulations. The person taking this survey should be familiar with your agency’s FOIA regulations and be able to provide citations. 
This survey should take no longer than 20 minutes to complete.
https://docs.google.com/forms/d/e/1FAIpQLSfFLQxq2U830ZMAo5LSiMHAxTBy0ApsEk7iL3g3aO0mpHbzdA/viewform
If you have questions about who should complete this survey, or if you have trouble taking it, please reach out to Matt.Gardner@usdoj.gov.

**Comment by adborden** [comment]
Looks good to me, @vz3 do you want to close this out?

**Comment by leahbannon** [comment]
lgtm
