### ISSUE TITLE
Agency form builder round 2 -- send and test

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#88]
As FOIA personnel within an agency, in order to communicate our perfected FOIA request needs, I need a way to validate fields and request new fields to populate the FOIA portal relevant to my agency.

This is for testing and scaling to our next round of agencies.

## Acceptance criteria

- [x] Get list of 10 agencies from OIP who are likely to get back to us fast, who didn’t have problems with the google form, and include some agencies with sub-components
- [x] Send email to them Monday
- [x] test and iterate
- [ ] incorporate changes for next round of agencies

**Comment by adborden** [comment]
This is just a one-time thing right? It's a one-off survey rather than a tool or a "form builder", right?

**Comment by vz3** [comment]
right this is why I've been calling it a survey.

**Comment by vz3** [comment]
dependency on #104
