### ISSUE TITLE
start outlining requester journey map and content needs

### ISSUE THREAD

**Issue by leahbannon** [usdoj/foia.gov#90]
As a requester, in order to create a request that can be processed quickly, I need to understand the difference between a simple and complex request at submission time.

As a requester, in order to understand what to expect from the FOIA process, I need to understand the time it will likely take to get my records before I hit submit. (MVP likely uses historical processing time data.)

As a requester, in order to submit my request to the right FOIA office the first time, I need an agency selector that helps me first select the agency, then drills down to the component level.

As a requester, in order to feel like my request is being handled as quickly as possible, I need a confirmation page after submission with a summary of my request and what to expect next.

As a requester, in order to submit my request to the right agency the first time, I need to understand why selecting the right FOIA office is important.

## Acceptance criteria

- [ ] journey map with phases/pages to build
- [ ] content requirements in each phase

**Comment by RyanSibley** [comment]
Work started here: https://docs.google.com/document/d/1ua5IIb2R5rJZr69h2NyDtt-B-i_bYhTAkaVz24zmUxU/edit

**Comment by RyanSibley** [comment]
Mural with phases in user journey outlined here: https://app.mural.ly/t/gsa6/m/gsa6/1504294441677/535e0fd39579d63e5a6192c94f80126cabe30c52

**Comment by RyanSibley** [comment]
@vz3 what do you think? Shall we close?

**Comment by vz3** [comment]
Yes this is 👍🏽
